### ISSUE TITLE
Remove Skylight as a forced dependency

### ISSUE THREAD

**Issue by jm** [Netflix/fast_jsonapi#10]
I'm all for having it available to those who need it, but it adds a lot of noise otherwise for those that don't.

**Comment by minsikzzang** [comment]
addressed here https://github.com/Netflix/fast_jsonapi/pull/14, just moved it to dev dependency with gem loading check rather than just removing.

**Comment by grossadamm** [comment]
PR Merged, I'm closing this. Please re-open if needed :)
