### ISSUE TITLE
Don't require id

### ISSUE THREAD

**Issue by aaronmallen** [Netflix/fast_jsonapi#100]
Currently, if a class that is being serialized does not have an attribute `id` an error `undefined method 'id'` is thrown.  IMO we should not have an opinion about what attributes are in the class at all.  This will allow for non-ActiveRecord classes to also be serialized.  At the very least, however, we should document that this is a required field.

**Comment by shishirmk** [comment]
id is a required key that needs to be there in a json-api response used to represent a resource
http://jsonapi.org/format/#document-top-level

Could you explain to me more about your usecase? is your id returned by a different method other than id?

**Comment by aaronmallen** [comment]
@shishirmk I'm a dumb and didn't really consider the json-api spec. Closing this.

**Comment by tilo** [comment]
```
Exception: The id member is not required when the resource object originates at the client and represents a new resource to be created on the server.
```

@shishirmk so why is this required in a POST transaction??
an id does not make any sense for a POST / create

This looks like a bug in fast_jsonapi

**Comment by FlyingGeese** [comment]
Is there any way we can choose not to require the id?

**Comment by stas** [comment]
@FlyingGeese nope, it's required by the spec:
https://jsonapi.org/format/#document-resource-object-identification

You can always mock it with some values from `securerandom` though...

**Comment by FlyingGeese** [comment]
@stas thanks. I'm pretty sure that I am mocking it though. I have it set up with this:

```
users = User.all
data = {"id": SecureRandom.hex(2), "type": "users", "all_users": users}
```

And I'm still getting the error

**Comment by TruRooms** [comment]
@rmdashrfv I ran into the same problem. Haven't looked into it, but using an `OpenStruct` instead of just a plain Hash worked well.

```
data = OpenStruct.new( id: SecureRandom.hex(2), type: 'users', all_users: users)
```

**Comment by mblumtritt** [comment]
Sorry to come back to this issue, but in the linked "[source of truth](https://jsonapi.org/format/#document-resource-objects)" is an explicit exception for the very usual case of creating a new object.

Do I have any chance when I re-open this ticket, @aaronmallen?

**Comment by stas** [comment]
@mblumtritt this project is no longer maintained, consider using the `jsonapi-serializer` gem.

Happy to merge the PR if you provide one.
