### ISSUE TITLE
Selecting attributes in associations

### ISSUE THREAD

**Issue by vadimstroganov** [Netflix/fast_jsonapi#101]
Hello!
Prompt, I can not understand, whether there is a possibility to select necessary attributes for the specified association?

```ruby
class MovieSerializer
  include FastJsonapi::ObjectSerializer
  set_type :movie
  attributes :name
  belongs_to :owner, attributes: [:name]
end
```

```json
{
  "data": {
    "id": "232",
    "type": "movie",
    "attributes": {
      "name": "test movie"
    },
    "relationships": {
      "owner": {
        "data": {
          "id": "3",
          "type": "user",
          "name": "Owner name example"
        }
      }
    }
  }
}
```

Is it possible to do this?

**Comment by CaioBianchi** [comment]
Same question here, but different issue...
I want to display data from a `has_many` relationship, but I'm only able to retrieve id and type. 
Is this intentional behaviour?

**Comment by hidde-jan** [comment]
This isn't how you would fetch these fields according to the jsonapi spec (see http://jsonapi.org/format/#document-resource-object-relationships and http://jsonapi.org/format/#document-resource-object-linkage). You would fetch the fields of the relationship object by including it:

    GET /api/movies/232?include=owner

**Comment by shishirmk** [comment]
@hidde-jan  has answered the question. I am going to close this issue as includes are supported and we already have sparse field set support in an open issue
