### ISSUE TITLE
Allow custom method or scope for includes

### ISSUE THREAD

**Issue by gsaks123** [Netflix/fast_jsonapi#108]
I think this suggestion is distinct from #47, but it's similar and could possibly be developed at the same time, if others agree and would find this valuable. Alternatively, if there is already a solution to this that would be even better 😄 

Scenario is as follows. This is for boxing/UFC fights where there are two athletes (fighters) in each bout, and many bouts in an event.

**Serializers:**
```
class FighterSerializer
  include FastJsonapi::ObjectSerializer
  attributes :first_name, :last_name
  has_many :fighter_bouts
end
```
```
class FighterBoutSerializer
  include FastJsonapi::ObjectSerializer
  attributes :date_of_event, :name_of_event, :result
end
```
**Models:**
```
class Fighter < ActiveRecord::Base
  has_many  :fighter_bouts

  def custom_method_with_scoping_and_eager_loading
    fighter_bouts.includes(<nested relationships>).where(<scoping of records>).order(<detailed ordering>)
  end
end
```
```
class FighterBout < ActiveRecord::Base
  belongs_to :fighter
  belongs_to :bout
end
```
```
class Bout < ActiveRecord::Base
  has_many    :fighter_bouts
  belongs_to  :event
  belongs_to  :weight_class
end
```

What I would like to be able to do is have an endpoint for a Fighter which is a compound document with included fighter_bouts.  Such as:

```
fighter = Fighter.find(1)
opts = {include: [:fighter_bouts]}
payload = FighterSerializer.new(fighter, opts).serialized_json
render json: payload
```

However, I want to use the custom method defined on the Fighter class, because it will eager load everything needed from a series of nested associations.  Data from these nested associations will be "flattened" and presented as attributes on the included fighter_bouts. For example, the event name will be returned as an attribute of a fighter_bout, even though in actuality this value is 2 associations away in the database.

Therefore I was thinking it would be very useful to be able to either pass an additional method name or value along with the options hash being given to the serializer.  Or, allow for a custom-named "association method" in the serializer.  Extremely roughly conceptualized as:

```
opts = {include: [:fighter_bouts_custom]}
payload = FighterSerializer.new(fighter, opts).serialized_json
```
```
class FighterSerializer
  include FastJsonapi::ObjectSerializer
  attributes :first_name, :last_name
  has_many :fighter_bouts

  def fighter_bouts_custom
    <reference to custom method on the Fighter class>
  end
end
```

Thanks for reading!

**Comment by shishirmk** [comment]
@gsaks123 we have the ability to customize the `object_method_name` and `id_method_name` for a has_many relationship. Here is the documentation https://github.com/Netflix/fast_jsonapi#customizable-options. Have you considered you these options?

**Comment by gsaks123** [comment]
@shishirmk Wow, I completely missed this. Yes, this is exactly the functionality I need.  Not only does the object_method_name scope the "relationships" payload, but it also applies (critically) to the  "included" payload. Perfect!

Thanks for your work on this gem.

**Comment by gsaks123** [comment]
Sure.  In this scenario we have an object class "Fighter", and when we call our API for a Fighter record, we want it to eager load and include a deeply nested association of other objects.  And that association is heavily scoped to only include certain results, with custom ordering.

Here is the custom method on our `app/models/fighter.rb` class which defines the scoping and the association. We want this logic to be applied to what is returned by our API:

```
  def ordered_fighter_bouts_api
    relation = fighter_bouts.includes( bout: [ {event: :promotion}, {fighter_bouts: :fighter}, :weight_class ] )
    relation = relation.where(status: Bout::STATUS_VISIBLE, sport: 'mma')
    relation.order("events.starts_at DESC", "bouts.bout_number_at_event DESC NULLS LAST", "bouts.id DESC")
  end
```

Then, in our serializer for Fighter records, `app/serializers/v1/fighter_serializer.rb`, we utilize the convenient 'object_method_name' that @shishirmk alerted me to:

```
class V1::FighterSerializer
  include FastJsonapi::ObjectSerializer
  has_many :fighter_bouts, object_method_name: :ordered_fighter_bouts_api
  attributes :first_name, :last_name, :middle_name, :nickname, :nationality
end
```

Lastly, in our controller for this API endpoint (`app/controllers/api/v1/fighters_controller.rb`), we include the Fighter's association using its basic/underlying class name. And it understands to use the object_method_name that was given in the serializer:

```
class Api::V1::FightersController < Api::BaseController
  def show
    fighter = Fighter.api_find_by_id(params[:id])
    head(:not_found) and return unless fighter
    payload = ::V1::FighterSerializer.new(fighter, {include: [:fighter_bouts]}).serialized_json
    render json: payload
  end
end
```

Does this help you and answer the questions you had?

**Comment by krzkrzkrz** [comment]
Yeap that explanation makes sense. I see how it works now. Thank you for that

However, I think this doesnt help my case. What I need to do, is call `object_method_name` with an arg. i.e. ideally passing `params` to it, so I can filter against it

**Comment by krzkrzkrz** [comment]
Actually, I figured this out. `has_many` supports blocks. ie.

```
  has_many :comments do |object, params|
    object.comments.where(status: params[:filter][:status])
  end

```

**Comment by batshoes** [comment]
Hey guys, struggling with this. I feel like I'm following this advice, the `object_method_name` sounds like exactly what I want but I'm not getting the details I expect. 

```
# lead_serializer.rb
class LeadSerializer
  include FastJsonapi::ObjectSerializer

  attributes :requested_amount, :loan_purpose ...

  has_many :products, object_method_name: :products_with_default
end

```

```
# lead.rb
class Lead < ApplicationRecord
...
  has_many :products, -> { unscope(:order).distinct },
           through: :matches, dependent: :nullify
...
  def products_with_default
    return products if products.present?
    Product.where("supported_loan_purposes ilike ?", "%#{loan_purpose}%")
  end
end
```

When I run these methods outside the serializer i.e.
```
$ Lead.first.products
=> []
$ Lead.first.products_with_default
=> 
[
  #<Product: 0x00007fdcbe33d810> {
    id: 1234
    ... 
  }
]
```
I get the expected outcome.
However my LeadSerializer is returning null for the products relationship

```
{
  :data => {
    :id            => "1234",
    :type          => :lead,
    :attributes    => {
      :requested_amount  => 10,
      :loan_purpose  => "general"
      ....
    },
    :relationships => {
      :account           => {
        :data => {
          :id   => "1234",
          :type => :account
        }
      },
      :products      => {
        :data => []
      }
    }
  }
}
```

Can someone point out what is going wrong with my configuration, or if there's a caveat I'm not aware of? Thank you!
