### ISSUE TITLE
Question on benchmark results 

### ISSUE THREAD

**Issue by pplant** [Netflix/fast_jsonapi#11]
I'm kind of courious where exactly or what makes fast_jsonapi 25x faster than AMS. Could you provide me some information on this?

It is clear that AMS probably generates some overhead due to a variety of features such as
custom attributes, adapters, conditionals and others. Eventhough the benchmark tests are only using the non-default adapter. E.g.: Only by removing this line of code and using the default adapter the execution times of AWS are dropping almost by 50%

    ActiveModel::Serializer.config.adapter = :json_api

Serializer      Records    Time
AMS serializer  1          1.25 ms
Fast serializer 1          0.14 ms

Serializer      Records    Time
AMS serializer  25         7.98 ms
Fast serializer 25         0.57 ms

Serializer      Records    Time
AMS serializer  250        73.46 ms
Fast serializer 250        2.64 ms

Serializer      Records    Time
AMS serializer  1000       322.16 ms
Fast serializer 1000       15.85 ms

Serializer      Records    Time
AMS serializer  1          0.55 ms
Fast serializer 1          0.13 ms

Serializer      Records    Time
AMS serializer  25         5.49 ms
Fast serializer 25         0.55 ms

Serializer      Records    Time
AMS serializer  250        63.45 ms
Fast serializer 250        4.77 ms

Serializer      Records    Time
AMS serializer  1000       282.82 ms
Fast serializer 1000       32.25 ms

**Comment by grossadamm** [comment]
It is entirely possible that AMS may be faster at serializing other formats, but we are focused on serializing to the jsonapi spec. It is also entirely possible that you don't want or need the jsonapi spec and that AMS is the better choice for you. That's ok :). 

This gem does not attempt to compete with AMS on the ability to output into multiple different formats or on the amount of customizability. 

Does that help explain the benchmarks better?

**Comment by andypike** [comment]
Out of curiosity, do you know how this compares with `jsonapi-rb` (http://jsonapi-rb.org)? We've started migrating from AMS to `jsonapi-rb` due to the performance improvements it gives. I'd be interested in how this compares also. 

Thanks!

**Comment by pplant** [comment]
@grossadamm first of all thanks for your replay. To be clear I'm not trying to troll you guys nor I'm a defender of AMS preaching it to be the silver bullet. On the contrary I think AWS is a major bottleneck in many APIs thats why I'm interested to understand what exactly makes fast_jsonapi more performant than AMS.

Apart from the possiblity in AMS to set different adapters which apparently have a variable impact on the performance of the serializiation what makes fast_jsonapi still ~10x-15x faster?

**Comment by grossadamm** [comment]
@andypike I think that's definitely worth comparing and benchmarking against! 

@pplant No offense taken at all :). In fact, it's these kind of discussions that I personally believe add the most value to the community. Asking why is incredibly important and could even lead to a better solution. To that end, I'm going to actually ask @shishirmk or @sriniwasgr to step in as they did most of the deep digging into why AMS was slower than what we wanted.

**Comment by grossadamm** [comment]
We are putting together a longer writeup, but in a nutshell, the gains were mostly found by focusing just on JSON API and homogenous lists.

**Comment by sriniwasgr** [comment]
@pplant Here is the [link](https://github.com/Netflix/fast_jsonapi/blob/master/performance_methodology.md) to the performance doc. Hopefully it helps in answering your question.

**Comment by pplant** [comment]
Thanks! Awesome write up. Think we can close this issue unless somebody else has further questions.
