### ISSUE TITLE
How to override the id attribute ?

### ISSUE THREAD

**Issue by Ranhiru** [Netflix/fast_jsonapi#113]
According to the JSON API specifications there must be an `id` field. But I do not want to expose the `id` column of my DB and I have a `friendly_id` column (which is unique as well).

How do I instruct fast_jsonapi to use my `friendly_id` column instead ?

**Comment by axsuul** [comment]
https://github.com/Netflix/fast_jsonapi/pull/54 enables you to render custom attributes and was recently merged in. 

You can point your `Gemfile` to the `dev` branch of this repo to use it.

**Comment by shishirmk** [comment]
This is not supported today. It should be relatively small change to the code are you willing to make a pull request?

**Comment by shuheiktgw** [comment]
PRed! https://github.com/Netflix/fast_jsonapi/pull/122

**Comment by shishirmk** [comment]
Released as a part of version 1.1.0
