### ISSUE TITLE
Is this a drop in replacement for active_model_serializers?

### ISSUE THREAD

**Issue by kapso** [Netflix/fast_jsonapi#115]
Coz the serializer (see below) is not working and I get this error - `NoMethodError (undefined method `order_date' for #<Order:0x00007fb6b78c4748>)`

active_model_serializers does allow you to attach attributes to local methods, looks like this gem does not allow this?

```ruby
class OrderSerializer
  include FastJsonapi::ObjectSerializer

  attributes :id, :total_price_cents, :order_date
  
  # order_date is not a method/attribute on Order model
  def order_date
    Time.current.to_s
  end
end
```

**Comment by citizen428** [comment]
#54 Adds a way to define custom attributes via a block, but there's been no gem release since this PR got merged.

**Comment by shishirmk** [comment]
It is not a drop in replacement for AMS. However it is very similar to AMS so it should be easy to migrate. However note that fast_jsonapi only serializes to json:api spec

**Comment by kapso** [comment]
@citizen428 any plans of doing it via a method. Block is nice, but a method has its advantages - mixins, inheritance to extend behavior.

**Comment by citizen428** [comment]
@kapso I don't know, I'm not a developer on this project, I just recently had the same question. There were alternative PRs but to the best of my knowledge none of them got merged yet.

**Comment by kapso** [comment]
@citizen428 thanks for the clarification.

@shishirmk any chances of merging changes that use a method instead of attribute block?

**Comment by guilleiguaran** [comment]
@kapso we will resume the discussion about custom methods and what's the best for implementing it after of 1.1.0 release 😊

**Comment by kapso** [comment]
@guilleiguaran got it, thanks. Whats the timeline for `1.1.0` release?

**Comment by shishirmk** [comment]
@kapso `1.1.0` has been released. Closing this as the question is answered. There is a separate open issue and pull request for supporting custom attributes through methods instead of block so i am going to close this issue.
