### ISSUE TITLE
1.1.0 release?

### ISSUE THREAD

**Issue by haizop** [Netflix/fast_jsonapi#120]
Is there a schedule for the 1.1.0 release? 

Apologies if this is an inappropriate use of an issue. I am eager to use this gem, and currently stuck waiting for custom attribute blocks added in [PR 54](https://github.com/Netflix/fast_jsonapi/pull/54).

Is there anything I can do to help move the release forward?

**Comment by shishirmk** [comment]
@haizop I am planning to release it this weekend. I will update the milestone info. The only things needed are backward compatibility for `use_hypen` feature that was part of the previous release.

**Comment by haizop** [comment]
@shishirmk  - Excellent. Thanks for the update, and thank you for your work on this awesome gem.

**Comment by shishirmk** [comment]
Released as a part of version 1.1.0
