### ISSUE TITLE
LoadError (cannot load such file -- yajl)

### ISSUE THREAD

**Issue by GarrisonD** [Netflix/fast_jsonapi#129]
Hello, guys!

I upgraded `fast_jsonapi` gem to the latest version that was released recently (v1.1) and didn't update anything else. As a result I have such error:

`LoadError (cannot load such file -- yajl)`

**Comment by GarrisonD** [comment]
As far as I understand, the error is here: https://github.com/Netflix/fast_jsonapi/blob/cf86cd871ecfe411d9c0fb22c85212b516a22138/lib/fast_jsonapi/multi_to_json.rb#L52

**Comment by zabodaevmm** [comment]
+
switching to 1.0.17 not to reproduce this error

**Comment by GarrisonD** [comment]
@zabodaevmm yeah, it's a workaround - but i like only solutions 😉

**Comment by GarrisonD** [comment]
If someone else run into this trouble and #130 is not still merged, then you can manually add `oj` gem to your project dependencies and enjoy features from `fast_jsonapi-v1.1`!

**Comment by shishirmk** [comment]
Looks like this needs to be a hot fix. @GarrisonD thank you for creating a pull request. I will look into and merge it as soon as i get a chance.

**Comment by shishirmk** [comment]
just released 1.1.1 with the above changes

**Comment by GarrisonD** [comment]
@shishirmk it's great news! thank you a lot!

**Comment by bf4** [comment]
@GarrisonD sorry about that. I wrote that bug :)
