### ISSUE TITLE
RubyGems not reporting correct date for releases

### ISSUE THREAD

**Issue by nneal** [Netflix/fast_jsonapi#136]
https://rubygems.org/gems/fast_jsonapi

I was looking at recent versions and trying to see which new versions have been released but RubyGems  is saying "Feb 1" for all versions. Maybe it's there issue or maybe it's yours. Just thought I'd point it out

**Comment by shishirmk** [comment]
@nneal Thank you for pointing it out. I am not sure how to fix it. If you come across a solution please share

**Comment by nneal** [comment]
I believe you should remove this line:
https://github.com/Netflix/fast_jsonapi/blob/master/fast_jsonapi.gemspec#L9

**Comment by shishirmk** [comment]
Will try that soon.

**Comment by ankit8898** [comment]
Should be fixed with #180 . Closing this one.
