### ISSUE TITLE
define key_transform anywhere in serializer

### ISSUE THREAD

**Issue by JohnBDonner** [Netflix/fast_jsonapi#138]
So after looking at https://github.com/Netflix/fast_jsonapi/issues/41#issuecomment-366931614 I noticed that we cannot call `set_key_transform` just anywhere in the serializer definition, but it must be called before defining attributes.

Unfortunately, I'd like to DRY up my serializers by inheriting all from an `ApplicationSerializer` and call `set_key_transform` there, but alas, it does not work.

Is there any way for us to fix this so we can do:
```ruby
class ApplicationSerializer
  include FastJsonapi::ObjectSerializer
  set_key_transform :camel
end
```

**Comment by fongfan999** [comment]
Hi @JohnBDonner ,
Here is my workaround

```ruby
class ApplicationSerializer
  def self.inherited(klass)
    klass.send :include, FastJsonapi::ObjectSerializer
    klass.send :set_key_transform, :camel
  end
end

class MySerializer < ApplicationSerializer
  # include FastJsonapi::ObjectSerializer
  # set_key_transform :camel
end

```

**Comment by JohnBDonner** [comment]
Hey @fongfan999, thanks for the workaround! It works great!
