### ISSUE TITLE
Add scope current_user like devise to check condition 

### ISSUE THREAD

**Issue by Phathdt** [Netflix/fast_jsonapi#145]
Would you mind if have option/scope for current_user to check condition and render ? 
example we have model User with attribute name, age, dob, secret_key
then we check current user 
if current user is normal => just render name, age, dob
if current user is admin => render name, age, dob, secret_key
and condition we can use some gem like rolify, pundit
any one know that?

**Comment by shishirmk** [comment]
fast_jsonapi doesn't have this functionality today of scopes. We would need to build it. Similar issue discussed in #139
