### ISSUE TITLE
`object_method_name` on `has_one` still trying to find `id`

### ISSUE THREAD

**Issue by cathykc** [Netflix/fast_jsonapi#146]
Hi!

Let me know if this is not the right forum for asking questions - happy to repost somewhere else.

1. I have three models, `A`, `B`, and `C`. 
2. `A` has_one `B`
3. `B` has_one `C`

I want to serialize `A` with `C` directly.

Here's what I am doing currently:
1. Creating a helper on `A`
```
def c_object
  b.c
end
```
2. using `has_one` in `A` serializer with `object_method_name`
```
has_one :c_object, object_method_name: :c_object, serializer: CSerializer
```

Though I've defined the helper to retrieve the C object in `A` the serializer is trying to find the `c_id` property directly on the `A` model and I'm getting this error:
```
NoMethodError: undefined method `c_object_id' for #<A:XXX>`
````

What's the right way to pull out nested objects from relationships like this?

**Comment by shishirmk** [comment]
@cathykc you would need two helper methods one for the id_method_name and other other one for object_method_name. If you are following convention you dont need to specify object_method_name and id_method_name.

define 2 helpers

```ruby
def c_object
   b.c
end

def c_object_id
   b.c_id
end
```

Add this line in the serializer

```ruby
has_one :c_object, serializer: CSerializer
```
We tend to just get the id wherever we can. This will helps in most cases as objects wont have to created just to get the id. However the case you describe above it would not be optmal

**Comment by cathykc** [comment]
A lil ugly but necessity understood @shishirmk thanks!
