### ISSUE TITLE
Nested model attributes

### ISSUE THREAD

**Issue by varkerkamachi** [Netflix/fast_jsonapi#172]
Hi team - I love the gem, definitely great speed. I'm struggling a little with the format of the output though, and it's probably something I'm doing wrong. 
I'm building a Rails 5 json api, and am trying to get more attributes included on the nested models than just `id` and `type`. Passing the model using `include:` on the controller just throws errors for me.

Gem:
```
bundle show fast_jsonapi
/Users/ac/.rvm/gems/ruby-2.4.1/gems/fast_jsonapi-1.1.1
```

Controller (this works fine):
```
class Api::V1::EventsController < ApplicationController
  expose(:search) {
    EventSearch.new({})
  }

  expose(:events) { search.results  }
  def index
    render json: Api::V1::EventSerializer.new(events).serializable_hash
  end
```

Serializer:
```
class Api::V1::EventSerializer
  include FastJsonapi::ObjectSerializer
  set_type :event
  attributes :id, :username, :kind
  belongs_to :user
```

This is giving me something like:
```
{"data":[{"id":"1","type":"event","attributes":{"id":1,...}, "relationships": {"user":{"data":{"id":"2","type":"user"}},...}]
```
But what I'd like it to be is more like:
```
{"data":[{"id":"1","type":"event","attributes":{"id":1,...}, "relationships": {"user":{"data":{"id":"2","type":"user","first_name":"Foo","last_name":"Baz",...}},...
```
(and whatever other attributes of this model I'd like to include)

I tried setting up my controller like below (doesn't work):
```
class Api::V1::EventsController < ApplicationController
  expose(:search) {
    EventSearch.new({})
  }

  expose(:events) { search.results  }
  def index
    render json: Api::V1::EventSerializer.new(events, include: [:user]).serializable_hash
  end
```
but this gives me the error:
```
curl -X GET -H "Accept: application/json" -H "Content-type: application/json" http://localhost:3000/api/v1/events
=> NameError in Api::V1::EventsController#index
=> uninitialized constant Api::V1::UserSerializer
```

Is there a way to do this using your gem and I'm messing it up, or is it limited to `id` and `type` only? 

Thanks,

**Comment by aldreth** [comment]
I think you probably want https://github.com/Netflix/fast_jsonapi#compound-document

**Comment by varkerkamachi** [comment]
Thanks @aldreth - appreciate that. It looks like what I'm trying to do indeed. Is there any other documentation available with examples of this compound document setup on the serializer end?
I did make the change you suggested, model & controller now look like: 
```
class Event < ApplicationRecord
  belongs_to :user
end
....

  def index
    options = {}
    options[:include] = [:users]
    render json: Api::V1::EventSerializer.new(events, options).serializable_hash
  ...
```
but now I'm getting 
```
ArgumentError (One of keys from [:users] is not specified as a relationship on the serializer):
```

I forked your repo and found the error but I'm not really understanding what the issue is. Is it necessary to list out all attributes of the associated models within the serializer, and if so do you have some syntax guides? I tried defining attributes for these associations  - inline, as a block - but nothing seems to work.

Thanks,

**Comment by kapso** [comment]
@varkerkamachi yes you need to define a `UserSerializer` with attributes for this to work.

Also I think it should be `options[:include] = [:user]` not `[:users]`

**Comment by kapso** [comment]
Also is there a way to have `attributes` on the relationship objects instead of having to use `include` for attributes on nested objects?

**Comment by shishirmk** [comment]
@kapso @varkerkamachi This gem only serializes based on the [jsonapi](http://jsonapi.org/) spec. This spec is doesnt nesting other attributes other than id and type. As @kapso rightly pointed out you are supposed to use includes for that. This helps avoid duplication of the same data in your response.

Closing this bug as this is out of scope of the [jsonapi](http://jsonapi.org/) spec
