### ISSUE TITLE
Set key transform doesn't transform record types in the included array

### ISSUE THREAD

**Issue by gabskoro** [Netflix/fast_jsonapi#182]
I'm using `set_key_transform :camel_lower` and everything is transformed well except the record type in the included array :)

![](http://skoro-attachments.s3.amazonaws.com/gabrijel/127.0.0.13000apiv1testing_2018-04-22_17-06-37.png)

**Comment by shuheiktgw** [comment]
What would happen if you would specify `serializer` option to relationships? For example, if you have a serializer like below, instead of defining relationship without serializer option

```
    CamelLowerMovieSerializer
        include FastJsonapi::ObjectSerializer
        set_key_transform :camel_lower
        belongs_to :movie_type
      end
```

specify the serializer like blow.

```
    CamelLowerMovieSerializer
        include FastJsonapi::ObjectSerializer
        set_key_transform :camel_lower
        belongs_to :movie_type, serializer: :camel_lower_movie_type
     end
```

Also, be aware that you need a serializer which explicitly defines set_key_transform.

```
    CamelLowerMovieTypeSerializer
        include FastJsonapi::ObjectSerializer
        set_key_transform :camel_lower
        has_many :movies
     end
```

Hope this would be of any help! 👍

**Comment by shishirmk** [comment]
@gabskoro I am not sure why @shuheiktgw 's suggestion wouldn't work. Would you be able to add a failing test?

**Comment by shishirmk** [comment]
@gabskoro is this an issue in the new version of the gem for you v1.2?

**Comment by shishirmk** [comment]
Closing due to no response

**Comment by chevinbrown** [comment]
@shishirmk this is an issue for me also. Has there been any development on this?

**Comment by chevinbrown** [comment]
@shishirmk the way this library sets the type keys for compound documents doesn't match up 1-1 with  AMS...is it possible to change key names?
