### ISSUE TITLE
Base class serializer should be picked up for STI models

### ISSUE THREAD

**Issue by mathieujobin** [Netflix/fast_jsonapi#183]
my application use SingleTableInheritence models, and using ActiveModelSerialiser, the parent class serializer is automatically picked up. with fast_jsonapi, a default built-in serializer is used, and thus mine is ignored.

models:

```ruby
class Animal < ActiveRecord::Base; end
class Cat < Animal; end
class Dog < Animal; end
class AnimalSerializer
  include FastJsonapi::ObjectSerializer
  attribute(:custom) { "we love ruby" }
end

class ZooController < ApplicationController
  def index
    render json: Animal.all
  end
end
```

my serializer was picked up with AMS but not this gem.

Thank you

**Comment by shishirmk** [comment]
@mathieujobin I was able to put together a pull request to make inheritance work as expected. #203  has the pull request for it

**Comment by mathieujobin** [comment]
sounds good, thanks
