### ISSUE TITLE
serializer option to disable `data` and `attributes` scoping

### ISSUE THREAD

**Issue by mathieujobin** [Netflix/fast_jsonapi#184]
we'd like to switch from AMS to using `fast_jsonapi` but we can't customize the json output the way we need to. 

our APIs are currently consumed, we can't just ask all api consumer to switch output format because we decided to use this gem.

fact is AMS let us output any json output we want while this gem is opinionated about the structured

we want to return simple structure such as 

`{"a":"11002458-818b-4ab8-a190-668630b4aed4","b":"815279f3-59d2-434a-9462-da87599840c5","c":0.0,"d":null}`

not 
`{"data":{"attributes":{"a":"11002458-818b-4ab8-a190-668630b4aed4","b":"815279f3-59d2-434a-9462-da87599840c5","c":0.0,"d":null}}}`

thank you

**Comment by shuheiktgw** [comment]
fast_jsonapi follows [JSON API](http://jsonapi.org/) format, and unfortunately I do not think you can change the format. However the good new is that AMS is not that slow compared with fast_jsonapi as long as you use default adaptor. See https://github.com/Netflix/fast_jsonapi/issues/118 👍

**Comment by mathieujobin** [comment]
Ah

**Comment by amol-edmodo** [comment]
we fixed AMS to FJA format as below by overriding `serializable_hash`

````
  def serializable_hash
    data = super

    if data[:data].is_a? Hash
      data[:data][:attributes]

    elsif data[:data].is_a? Array
      data[:data].map{ |x| x[:attributes] }

    elsif data[:data] == nil
      nil

    else
      data
    end
  end

````

**Comment by amolpujari** [comment]
we fixed AMS to FJA format as below by overriding `serializable_hash`

````
  def serializable_hash
    data = super

    if data[:data].is_a? Hash
      data[:data][:attributes]

    elsif data[:data].is_a? Array
      data[:data].map{ |x| x[:attributes] }

    elsif data[:data] == nil
      nil

    else
      data
    end
  end

````

**Comment by truonglocbinh9x** [comment]
@amolpujari what file I put your code to ? Can you give me a example ?

**Comment by mathieujobin** [comment]
This is really sweet thank you.

When I get a chance. I might turn this into an Option

**Comment by amolpujari** [comment]
````
# app/serializers/application_serializer.rb

class ApplicationSerializer
  include FastJsonapi::ObjectSerializer
  #cache_options enabled: true, cache_length: 1.hour

  def to_h
    data = serializable_hash

    if data[:data].is_a? Hash
      data[:data][:attributes]

    elsif data[:data].is_a? Array
      data[:data].map{ |x| x[:attributes] }

    elsif data[:data] == nil
      nil

    else
      data
    end
  end

  class << self
    def has_one resource, options={}
      serializer = options[:serializer] || "#{resource.to_s.classify}Serializer".constantize

      attribute resource do |object|
        serializer.new(object.try(resource)).to_h
      end
    end

    def has_many resources, options={}
      serializer = options[:serializer] || "#{resources.to_s.classify}Serializer".constantize

      attribute resources do |object|
        serializer.new(object.try(resources)).to_h
      end
    end
  end
end

````
