### ISSUE TITLE
CodeClimate + Rubocop + Test Coverage

### ISSUE THREAD

**Issue by oniofchaos** [Netflix/fast_jsonapi#189]
Is there any opposition to adding CodeClimate, Rubocop, and Test Coverage metrics?

**Comment by shishirmk** [comment]
Go Ahead

**Comment by oniofchaos** [comment]
For CodeClimate, it looks like the owner(s) of the repo/organization need to administer it - https://docs.codeclimate.com/docs/open-source-free

**Comment by oniofchaos** [comment]
For test coverage, the two most user friendly ways that I know of are through CodeClimate or through Coveralls, which I think also needs an owner to set it up. 

Rubocop can technically be added separately but if it's bundled with CodeClimate you get nice visual results of the issues.

TL;DR sounds like I'd need admin/owner rights to help out with the setup - totally understand if you want to handle that internally instead.
