### ISSUE TITLE
Conditional attributes in Serializer

### ISSUE THREAD

**Issue by Branksy** [Netflix/fast_jsonapi#191]
Say I have one UserSerializer.
How can I display a different set of attributes in the serializer depending on the context, e.g. show action v. index action, without creating two separate serializers?
Thanks.

**Comment by alienxp03** [comment]
Looking forward to this feature too. Related PR I supposed? https://github.com/Netflix/fast_jsonapi/pull/153

**Comment by shishirmk** [comment]
#153 has been merged to dev

**Comment by alienxp03** [comment]
Awesome. Thanks @shishirmk

**Comment by TrevorHinesley** [comment]
#153 does not include this functionality unfortunately. Right?

**Comment by shishirmk** [comment]
Duplicate of #185
