### ISSUE TITLE
Senior Platform Engineer link in the README.md is broken.

### ISSUE THREAD

**Issue by ohbarye** [Netflix/fast_jsonapi#209]
I just found that [Senior Platform Engineer](https://jobs.netflix.com/jobs/865783) link in the README.md is broken. When I visit https://jobs.netflix.com/jobs/865783, it redirects me to https://jobs.netflix.com/search.

**Comment by ankit8898** [comment]
@ohbarye Ah! Thanks for bringing to attention. That position is closed but the other is open. Do you want to PR removing dead link? I will close this issue and will fix via PR.

**Comment by ohbarye** [comment]
> Do you want to PR removing dead link?

Yeah, I do!
