### ISSUE TITLE
Caching: race condition ttl

### ISSUE THREAD

**Issue by Daniel-ltw** [Netflix/fast_jsonapi#21]
Rails.cache.fetch might need a race_condition_ttl option? 

> Setting :race_condition_ttl is very useful in situations where a cache entry is used very frequently and is under heavy load. If a cache expires and due to heavy load several different processes will try to read data natively and then they all will try to write to cache. To avoid that case the first process to find an expired cache entry will bump the cache expiration time by the value set in :race_condition_ttl. Yes, this process is extending the time for a stale value by another few seconds. Because of extended life of the previous cache, other processes will continue to use slightly stale data for a just a bit longer. In the meantime that first process will go ahead and will write into cache the new value. After that all the processes will start getting the new value. The key is to keep :race_condition_ttl small.

**Comment by grossadamm** [comment]
This makes sense to me!

**Comment by shishirmk** [comment]
This should be released in version 1.2 of the gem
