### ISSUE TITLE
Render without root key, id and type?

### ISSUE THREAD

**Issue by alienxp03** [Netflix/fast_jsonapi#217]
- Is there a way to only render the attributes, without the root key `data`, `id`, and `type`?
- A way to define custom root key?

Instead of 
```ruby
{
  "data": {
    "id": "3",
    "type": "movie",
    "attributes": {
      "name": "test movie",
      "year": null
    },
}
```

I'm hoping to produce
```ruby
{
  "attributes": {
      "name": "test movie",
      "year": null
  }
}
```

One of my solution is to use a helper instead to get just the attributes
```ruby
module SerializerHelper
  def attributes
    serializable_hash[:data][:attributes]
  end
```

Also by doing this, I can provide my own root key because in some cases, the JSOn I'm returning is not an ActiveModel record

**Comment by guilleiguaran** [comment]
Those things aren't supported out-of-box because they don't comply with [JSON:API spec](http://jsonapi.org/)

**Comment by alienxp03** [comment]
Thanks for clarifying that. Is there any plan to support multiple rendering options? For AMS, they're using the concept of different [adapters](https://github.com/rails-api/active_model_serializers/blob/v0.10.6/docs/general/adapters.md#built-in-adapters)

I'm currently using a different gem and thinking to give `fast_jsonapi` a try. Mostly due to its performance. But to rewrite it to JSON:API spec, it also means I need to rewrite my client applications.

 If there are no such plans, should be ok with me to customize it on my own. Thanks a lot for the fast response :)

**Comment by shishirmk** [comment]
@alienxp03 there are no such plans in the near future
