### ISSUE TITLE
Skylight Integration Suggestions

### ISSUE THREAD

**Issue by wagenet** [Netflix/fast_jsonapi#22]
As one of the lead developers on Skylight it's awesome to see you integrating it!

This is probably a bit counter to our own self-interest, but I think it would probably make a bit more sense if, instead of using `Skylight::Helpers` you just use `ActiveSupport::Notifications`. You could then set up a `Skylight::Normalizer` to consume the events if Skylight was present or other libraries could use them as well. We haven't really flushed out a public API for adding Normalizers so this is definitely something I'd be happy to discuss with you if you're interested.

**Comment by sriniwasgr** [comment]
@wagenet thanks for the suggestion.  We will definitely add this to the roadmap.

**Comment by wagenet** [comment]
Awesome, just ping me when you've got some time to chat about it. Looks like you do some Ember stuff so you can grab me on the Ember Community Slack if you're there. I'll also be at EmberConf and RailsConf if you'll be at either. Or we can keep chatting here of course.

**Comment by poteto** [comment]
@wagenet We do a little bit ;)

**Comment by hmcfletch** [comment]
I opened #61 to take a crack at this.

**Comment by shishirmk** [comment]
@wagenet Do you mind taking a look at @hmcfletch's pull request. From a skylight point of view would it work just the same way as `instrument_method` works?

**Comment by hmcfletch** [comment]
@wagenet I'd love some pointers on normalizers/probes. The AS notifications were easy enough, but not really sure about the normalizers and probes.

**Comment by wagenet** [comment]
I'll try to give it a look today.

**Comment by shishirmk** [comment]
Released as a part of version 1.1.0
