### ISSUE TITLE
Lookup for STI models

### ISSUE THREAD

**Issue by stelmashchuk** [Netflix/fast_jsonapi#225]
First of all thanks for the great gem)
I use Single Table Inheritance in my project. 

```ruby
class Song < ActiveRecord::Base; end
class Pop < Song; end
class Rock < Song; end

class SongSerializer
  include FastJsonapi::ObjectSerializer
  attribute :title
end
class PopSerializer < SongSerializer
  attribute :description
end
class RockSerializer < SongSerializer
  attribute :duration
end
```
```ruby
@songs = [PopModel, RockModel]
render json: @songs
```

AMS makes automatic lookup and returns JSON with items with different attributes(```title, description``` for ```PopModel```; ```title, duration``` for ```RockModel```). 
Do you plan to add functionality like this? Thank you.

**Comment by shishirmk** [comment]
@stelmashchuk we haven't worked on making the serializer work with heterogenous lists of models like the one you described above. It's not something we are looking into at the moment

**Comment by stelmashchuk** [comment]
Thanks for answer

**Comment by vivektiwary** [comment]
@shishirmk Is there any progress in this, are you guys thinking about giving this functionality?

**Comment by top4ek** [comment]
Same question. Need to serialize a bunch of STI records with different attributes inherited.
