### ISSUE TITLE
Questions about some features

### ISSUE THREAD

**Issue by imadmoussa1** [Netflix/fast_jsonapi#227]
Hello,
I using the AMS gem, and  I am switching to Fast JSON api .
I have  some questions about those features :
1.  About the includes , with AMS i was using `include: '*'` and `include: '**'`
do you have something similar to it ?

2. Can we add meta in the serializer class ?
`meta do
    { message: "sucess", total_count: object.total_count }
  end`

3. Can we rename the attribute ?
`attribute :text, key: :label`

**Comment by TrevorHinesley** [comment]
I don't know about the first two, but I believe for 3 you'd just:

```
attribute :label do |object|
  object.text
end
```

**Comment by shishirmk** [comment]
>About the includes , with AMS i was using include: '*' and include: '**'
do you have something similar to it ?

No we don't have this feature. Happy to assist if you would like to make pull request to support these features.

>Can we add meta in the serializer class ?
You should be able to pass anything to the meta has as shown [here](https://github.com/Netflix/fast_jsonapi#compound-document)

**Comment by imadmoussa1** [comment]
@shishirmk Thank you , I will work on it .
