### ISSUE TITLE
has_many N+1 due to relationships and fetch_multi support

### ISSUE THREAD

**Issue by vkozyrev** [Netflix/fast_jsonapi#228]
Suppose I have a `Candidate` object that is returned. This object `has_many :work_histories`.
When I `INDEX (GET candidates/`, something like the following is returned
```
{
            "id": "058ab5e3-de71-4d79-8923-571934f91b58",
            "type": "candidate",
            "attributes": {
                "id": "058ab5e3-de71-4d79-8923-571934f91b58",
                "type": "Candidate",
                "first_name": "Vlad"
            },
            "relationships": {
                "work_histories": {
                    "data": [
                        {
                            "id": "00c61bdf-ae70-49b4-9776-3c3cb3cf799a",
                            "type": "work_history"
                        },
                        {
                            "id": "7732f7b0-53b7-45c7-950e-5d461836854d",
                            "type": "work_history"
                        },
                        {
                            "id": "c7b4f103-9b88-4d32-a241-5d9e52cdb54d",
                            "type": "work_history"
                        }
                    ]
                }
        },
        { 19 more objects similar to above }
}
```
Since we return `work_history ids` for 20 `Candidate` objects, my logs look like:
```
(4.6ms)  SELECT "work_histories"."id" FROM "work_histories" WHERE "work_histories"."deleted_at" IS NULL AND "work_histories"."candidate_id" = $1  [["candidate_id", "058ab5e3-de71-4d79-8923-571934f91b58"]]
  ↳ /Users/vkozyrev/Documents/Rainmakers/fast_jsonapi/lib/fast_jsonapi/serialization_core.rb:188
Cache read: candidates/416f66aa-f8f7-48f2-8231-4bfa1d26113f-20180518031146912393 ({:expires_in=>12 hours, :race_condition_ttl=>5 seconds})
Cache fetch_hit: candidates/416f66aa-f8f7-48f2-8231-4bfa1d26113f-20180518031146912393 ({:expires_in=>12 hours, :race_condition_ttl=>5 seconds})
   (4.8ms)  SELECT "work_histories"."id" FROM "work_histories" WHERE "work_histories"."deleted_at" IS NULL AND "work_histories"."candidate_id" = $1  [["candidate_id", "416f66aa-f8f7-48f2-8231-4bfa1d26113f"]]
  ↳ /Users/vkozyrev/Documents/Rainmakers/fast_jsonapi/lib/fast_jsonapi/serialization_core.rb:188
Cache read: candidates/69460f05-e6ea-447a-95a2-3ba9029c1b6b-20180524192747106416 ({:expires_in=>12 hours, :race_condition_ttl=>5 seconds})
Cache fetch_hit: candidates/69460f05-e6ea-447a-95a2-3ba9029c1b6b-20180524192747106416 ({:expires_in=>12 hours, :race_condition_ttl=>5 seconds})
   (5.3ms)  SELECT "work_histories"."id" FROM "work_histories" WHERE "work_histories"."deleted_at" IS NULL AND "work_histories"."candidate_id" = $1  [["candidate_id", "69460f05-e6ea-447a-95a2-3ba9029c1b6b"]]
  ↳ /Users/vkozyrev/Documents/Rainmakers/fast_jsonapi/lib/fast_jsonapi/serialization_core.rb:188
Cache read: candidates/d20db4b2-f217-4635-a259-f96bae44eb32-20180517183429084408 ({:expires_in=>12 hours, :race_condition_ttl=>5 seconds})
Cache fetch_hit: candidates/d20db4b2-f217-4635-a259-f96bae44eb32-20180517183429084408 ({:expires_in=>12 hours, :race_condition_ttl=>5 seconds})
...
...
... few more times
```

So with the above situation, I have a few questions:

* Since I am not actually including the `WorkHistory` objects, I don't really care about seeing the `ids`. Is there a way to disable the relationships section of the serialization unless that model is specifically included in the options? What are your thoughts on this? 
  * `.includes(:work_histories)` fixes N+1, but I don't necessarily wan't to `.includes` all `has_many` relationships unless they are actually needed

* Doesn't the above also mean that if a `Candidate` has thousands of `WorkHistories`, all the ids would be serialized and listed in relationships?

* Are you looking into implementing `fetch_multi` support to help with the N+1 cache read of `INDEX` actions?

Overall this is shaping up to be a great looking gem! I'm in the process of transitioning my code from AMS, and this has been amazing in terms of amount of rewrite needed to switch. I could be open to trying to tackle some of the above issues depending on the responses I get.

Thanks!

**Comment by shishirmk** [comment]
>Is there a way to disable the relationships section of the serialization unless that model is specifically included in the options? What are your thoughts on this?

No not really. there is nothing in the [jsonapi spec](http://jsonapi.org/) about showing has_many ids only if the records are included. However you could achieve something like this using the relationship block and passing in appropriate [params](https://github.com/Netflix/fast_jsonapi#params)

> Doesn't the above also mean that if a Candidate has thousands of WorkHistories, all the ids would be serialized and listed in relationships?

But that is how the spec works today. Again you could use the relationship block to define this relationship anyway you would like (for example only show top 10 etc)

> Are you looking into implementing fetch_multi support to help with the N+1 cache read of INDEX actions?

I would be curious to understand what kind of support would be needed. Please provide examples

**Comment by vkozyrev** [comment]
Hey. I missed the part in the docs about being to use a block for relations. Thanks for pointing that out.

I'll follow up about fetch_multi in a separate issue after I look into it more.
