### ISSUE TITLE
Sequel gem compatibility

### ISSUE THREAD

**Issue by trueinviso** [Netflix/fast_jsonapi#229]
If an app is using the Sequel gem as their ORM adapter, a model instance will have `each` defined on it, for the purpose of iterating all values on that particular instance.  

This will prevent the serialization of model instances when `FastJsonapi::ObjectSerializer` calls `is_collection?` [here](https://github.com/Netflix/fast_jsonapi/blob/master/lib/fast_jsonapi/object_serializer.rb#L84), from the `serializable_hash` method.

    def is_collection?(resource)
      resource.respond_to?(:each) && !resource.respond_to?(:each_pair)
    end

Perhaps `size` would also achieve the same effect here? 

`resource.respond_to?(:size) && !resource.respond_to?(:each_pair)`

**Comment by shishirmk** [comment]
@trueinviso we can try size and see if tests fail. Go ahead and make a pull request if that works

**Comment by trueinviso** [comment]
PR #234

**Comment by shishirmk** [comment]
This feature is released in [version 1.3](https://github.com/Netflix/fast_jsonapi/releases/tag/1.3)
