### ISSUE TITLE
polymorphic: true is not implemented for nested includes

### ISSUE THREAD

**Issue by jshow** [Netflix/fast_jsonapi#231]
https://github.com/Netflix/fast_jsonapi/blob/master/lib/fast_jsonapi/serialization_core.rb#L150

Can someone please help me understand what the challenge is here ?

I built nested includes, and have just moved to using the master branch - not sure why the raise is protecting ?

really need this.

thanks

**Comment by shishirmk** [comment]
@jshow it didn't work in a test so i just added the NotImplementedError. I think the challenge might be to find the right serializer and call record_hash on it.

**Comment by jshow** [comment]
thank you @shishirmk , I'll investigate

**Comment by jshow** [comment]
How does this look ? https://github.com/Netflix/fast_jsonapi/pull/275

**Comment by shishirmk** [comment]
Released in [Version 1.4](https://github.com/Netflix/fast_jsonapi/releases/tag/1.4)
