### ISSUE TITLE
How does fast_jsonapi get so fast?

### ISSUE THREAD

**Issue by yjukaku** [Netflix/fast_jsonapi#241]
Great work on this gem! I've read through the blog posts and the `performance_methodology` page, and it seems that a lot of the performance gains here are due to the fact that

1. fast_jsonapi is focused only on the json-api spec, so doesn't have to be flexible.
2. fast_jsonapi only allows for homogenous lists of items

However, I'm interested in knowing _how_ you were able to take advantage of these two facts to increase speed so immensely. I'd rather not have to manually compare AMS's source to FJA's source, and try to figure it out myself 😄 Any blog posts, articles, etc?

**Comment by shishirmk** [comment]
We don't have a blogpost or anything going into the details of _how exactly_ the performance improvement was seen. There isn't one neat trick which resulted in the performance gains.  Here are some points of the top of my head that helped us improve the performance

- Caching the attribute definitions, relationship definitions, key transforms  etc makes serializing homogeneous lists faster.  
- We don't create objects whenever we can avoid object creation for example when we just need ids of has_many, belongs_to, has_one relationships we just get the ids. 
- Having performance tests from the beginning helped us understand the performance impact of features we built and so we tried to address these issues early and often in the development cycle.
