### ISSUE TITLE
belongs_to :user doesn't show fields in the serializer

### ISSUE THREAD

**Issue by LucasCioffi** [Netflix/fast_jsonapi#242]
Hello, great gem!

A user can have many designs.  In #user.rb: `has_many :designs` In design.rb `belongs_to :user`

I'm wondering why when I use `belongs_to :user, serializer: :user` I don't see the custom attributes specified in the UserSerializer (it returns ID and type only).

When I specifically call the UserSerializer as an attribute, the correct fields are visible.  You can see both used below with different output:
```
class DesignSerializer
  include FastJsonapi::ObjectSerializer

  attributes :name
  attribute :user do |object|
    UserSerializer.new(object.user)
  end
  belongs_to :user, serializer: :user
 # same results for belongs_to :user, serializer: UserSerializer
end
```

```
> DesignSerializer.new(Design.last).serialized_json 
{
	"data": {
		"id": "72",
		"type": "design",
		"attributes": {
			"name": "My Design Name",
			"user": {
				"data": {
					"id": "22",
					"type": "user",
					"attributes": {
						"email": "hi@ya.com",
						"source": "abc",
						"source_id": null
					}
				}
			}
		},
		"relationships": {
			"user": {
				"data": {
					"id": "22",
					"type": "user"
				}
			}
		}
	}
}
```

**Comment by shishirmk** [comment]
@LucasCioffi this gem only supports[ jsonapi.org](http://jsonapi.org/) json schema. The above serialization is not compliant with jsonapi.org json schema. 

If you want other attributes of a relationship try to sideload them using [includes](http://jsonapi.org/format/#fetching-includes)

**Comment by LucasCioffi** [comment]
Hello @shishirmk, thank you for your reply.

The question I have is about why `belongs_to :user, serializer: UserSerializer` doesn't seem to pick up the formatting specified in the `UserSerializer`.

For example, if the `DesignSerializer` looks like this:
```
class DesignSerializer
  include FastJsonapi::ObjectSerializer

  attributes :name
  belongs_to :user, serializer: UserSerializer
end
```
and if the `UserSerializer` looks like this:
```
class UserSerializer
  include FastJsonapi::ObjectSerializer
  attributes :email
end
```
... then `DesignSerializer.new(Design.last).serialized_json` returns this (notice the user's email is missing):
```
 => "{\"data\":{\"id\":\"79\",\"type\":\"design\",\"attributes\":{\"name\":\"Name of Design\"},\"relationships\":{\"user\":{\"data\":{\"id\":\"27\",\"type\":\"user\"}}}}}" 
```
However if I change the `DesignSerializer` to this:
```
class DesignSerializer
  include FastJsonapi::ObjectSerializer

  attributes :name
  attribute :user do |object|
    UserSerializer.new(object.user)
  end
end
```
then the output does reflect what's in the `UserSerializer` (specifically, the user's email is included):
```
 => "{\"data\":{\"id\":\"79\",\"type\":\"design\",\"attributes\":{\"name\":\"Name of Design\",\"user\":{\"data\":{\"id\":\"27\",\"type\":\"user\",\"attributes\":{\"email\":\"me@example.com\"}}}}}}" 
```

*So that indicates to me that the `UserSerializer` is set up correctly but not being referenced correctly.  Is that what you think is happening?*

Does this info provide a clue about what is wrong?  If I replace `belongs_to :user, serializer: UserSerializer` with `belongs_to :user, serializer: WrongUserSerializer` I see this error: `NameError: uninitialized constant DesignSerializer::WrongUserSerializer` so that makes me think that `belongs_to :user, serializer: UserSerializer` is correctly referring to `UserSerializer`, however it's not returning the user's email address as specified in that user serializer.

The files are located here:
`app/serializers/design_serializer.rb`
`app/serializers/user_serializer.rb`

Would you expect that `belongs_to :user, serializer: UserSerializer` would successfully display the user's email address since `UserSerializer.new(User.last).serialized_json` successfully returns this?
```
=> "{\"data\":{\"id\":\"27\",\"type\":\"user\",\"attributes\":{\"email\":\"me@example.com\"}}}" 
```

**Comment by ChrisHampel** [comment]
This is following the JSON API specifications. In this specification, unless you tell it to, it will just put enough information to be able to look up the related resources. As shown in this section of the Readme [Compound Documents](https://github.com/Netflix/fast_jsonapi/blob/master/README.md#compound-document) you must pass in an options hash with the key include containing which associations you want to include in this response. In your example that would be:

DesignSerializer.new(Design.last,{include: :user}).serialized_json .

by doing so you will get a new root key in your JSON responce called included which will contain an array of any related resources you specified to include.

It is in a separate section of the response as per the specification linked below. The reason for the separate section is that. it is possible to have the same resource referenced multiple times in the response, and listing the whole resource only once uses fewer bytes, resulting in a smaller final response.

related specification: http://jsonapi.org/format/#document-compound-documents .

**Comment by LucasCioffi** [comment]
@ChrisHampel thank you so much for the detailed response!

`DesignSerializer.new(Design.last, {include: :user}).serializable_hash` gives me this error:
`NoMethodError: undefined method `delete_if' for :user:Symbol`
which seems to be coming from `process_options(options)` in lib/fast_jsonapi/object_serializer.rb

Is it clear to you what might be wrong?  Thank you; I appreciate it!

**Comment by ChrisHampel** [comment]
sorry about that I was writing that at 6 am it should be an array {include: [:user]}

**Comment by LucasCioffi** [comment]
Thanks, @ChrisHampel!

**Comment by LuisHCK** [comment]
@ChrisHampel Thanks, _include_ works for me.
