### ISSUE TITLE
Make Relationships optional.

### ISSUE THREAD

**Issue by esiegel** [Netflix/fast_jsonapi#247]
When a serializer has lots of associations it can sometimes be costly to make the additional DB queries to fetch the `type`: `id` pairs.  From looking at the spec and from reading the [JSON Api forum](https://discuss.jsonapi.org/t/is-it-valid-to-exclude-relationships-from-a-relationships-object/290), it seems like it isn't a requirement to always include the relationships, or include the pairs.  You could instead return a relationship link that a client could query.

I'm not sure what the best solution would be, but it would be nice to offer this level of control to users of this library.   We could, as an example, add a `relationship_serializer` option that does magic.

**Comment by shishirmk** [comment]
You could send relationship links using this option https://github.com/Netflix/fast_jsonapi#links-per-object. To optionally include a relationship or attribute is a feature that needs to be  worked on.

**Comment by krzkrzkrz** [comment]
Looking forward to this as well

**Comment by shishirmk** [comment]
Optionally including an attribute or a relationship called sparse fieldsets feature is ready. This feature is released in [version 1.3](https://github.com/Netflix/fast_jsonapi/releases/tag/1.3)
