### ISSUE TITLE
Key transforms not called on the record type of included objects

### ISSUE THREAD

**Issue by djohnson** [Netflix/fast_jsonapi#248]
When key_transform is set to anything other than `underscore` and `set_type` is not manually called and includes are requested then the includes object types are not transformed as expected.  

Looking in the code I see that `set_type` is called via inclusion into the class and even attempts to use the `run_key_transform` lookup, but given the code load/run order it will never be transformed.  You can call `set_type` manually after setting `key_transform` and it will be transformed as expected, but given that this is optional it should not be required for `key_transform` to function properly and it definitely shouldn't depend on the calling order of `key_transform` and `set_type`.

**Comment by shishirmk** [comment]
Yes this is a known issue we need to build a fix for this issue and get it released.

**Comment by shishirmk** [comment]
thanks @djohnson for the pull request

**Comment by shishirmk** [comment]
This feature is released in [version 1.3](https://github.com/Netflix/fast_jsonapi/releases/tag/1.3)
