### ISSUE TITLE
Exclude data from relationships

### ISSUE THREAD

**Issue by krzkrzkrz** [Netflix/fast_jsonapi#252]
Couldnt find this in the doc. Wondering if there is a way to exclude the `data` node from relationships. Especially helpful for `has_many` associations with a ton of `data`, which makes the payload even larger.

Instead, have the option to include `links.related`

Would be nice if there was something like `has_many :comments, exclude: [:data], include: [:'links.related']`

By `links.related` in `relationships`. I mean something like:

```
"attributes": {
  ...
},
"relationships": {
  "comments": {
    "links": {
      "related": "http://localhost/api/v1/users/1/comments"
    }
},
```

**Comment by shishirmk** [comment]
@krzkrzkrz we dont have a way to do this.. sparse fieldsets should solve for this. That will be in our next release

**Comment by krzkrzkrz** [comment]
Great to hear. Will close for now

**Comment by ahx** [comment]
I have re-opened this in https://github.com/Netflix/fast_jsonapi/issues/357
