### ISSUE TITLE
Having a hard time understanding usage of object_method_name

### ISSUE THREAD

**Issue by krzkrzkrz** [Netflix/fast_jsonapi#255]
Current docs doesnt really explain too much about `object_method_name`

Doc shows something like: `has_many :locations, object_method_name: :places`

But where exactly should `places` be defined? In the model? I have something similar defined in my model. But doesnt look like this method is being executed

**Comment by shishirmk** [comment]
@krzkrzkrz  yes it should be defined in the model. Could you give more information about why that is not working for you?

**Comment by krzkrzkrz** [comment]
I "partially" found my answer at https://github.com/Netflix/fast_jsonapi/issues/108

We can continue discussion there if you would like and we can close this?
