### ISSUE TITLE
Possible to make ids return as integers?

### ISSUE THREAD

**Issue by krzkrzkrz** [Netflix/fast_jsonapi#258]
As the title says. Possible to make ids return as integers? Maybe a configuration somewhere in the serializer?

**Comment by krzkrzkrz** [comment]
Hmm, just realized. This is possible with `set_id`.

i.e. `set_id :id_to_s`

Then in the model:

```
  def id_to_s
    self.id.to_s
  end
```

**Comment by ababich** [comment]
This is here
https://github.com/Netflix/fast_jsonapi/blob/dev/lib/fast_jsonapi/serialization_core.rb#L31

and actually frominitial commit from @shishirmk 
https://github.com/Netflix/fast_jsonapi/commit/5374a1378ec3269b6267346001b32083ada9bd5a#diff-0d22ea72f1e72c75e7887cdbcba46871R22

may be he can add some light why this is done this way

**Comment by guilleiguaran** [comment]
It's done in that way per JSON:API spec: http://jsonapi.org/format/#document-resource-object-identification

>Every resource object **MUST** contain an _id_ member and a _type_ member. The values of the _id_ and _type_ members **MUST** be strings.

**Comment by ababich** [comment]
@guilleiguaran great comment!

But I agree with topic starter that this makes not much sense

**Comment by krzkrzkrz** [comment]
Yea looks to be that strings are standard. Unfortunately, our API returns ids as integers. Changing to strings might require a huge refactor on the clients. 

Until all clients manage to adapt. I guess the only way is to fork this repo and change the line at https://github.com/Netflix/fast_jsonapi/blob/dev/lib/fast_jsonapi/serialization_core.rb#L31
