### ISSUE TITLE
Usage question on operations with nested objects

### ISSUE THREAD

**Issue by alosada** [Netflix/fast_jsonapi#268]
Hello!

Lets say I have a model called `budget`, where `budget` has_many `items` and on my index, i need to display both the count of `items` as well as the sum of `item.price` so I get:
```
{data:
  0:{
    id: 42,
    type: 'budget'
    attributes:
     { ......
     items: 9,
     total: 1798.99
     .......
     }
  }
}
```

I'm wondering whats the best way to accomplishing this?

Currently I'm using the custom `attribute` to perform the math resulting on N+1 queries

**Comment by ababich** [comment]
If you do **not** have these values pre-calculated (which I'd recommend as a solution)
in most other cases you can do it in initial request via aggregation in corresponding query language (SQL, for ex.),
but exact implementation depends on your data storage (RDBMS, for ex.)
and toolkit you're using to query it (Sequel, ActiveRecord, for ex.)

**Comment by ababich** [comment]
The question is out of gem scope, you should close it and ask in some proper place (stackoverflow.com, for ex.) to dig into solution details

**Comment by shishirmk** [comment]
Agree with @ababich
