### ISSUE TITLE
record_type not working for associations

### ISSUE THREAD

**Issue by aphilippartd** [Netflix/fast_jsonapi#270]
Hi,

I am currently facing an issue when trying to include a certain nested record in one of my serialization. I have two serializers: a ContractSerializer and a LegalEntitySerialiser. Each of my legal entities can either be a owner or a tenant. On my Contract model, I have a `has_many :tenants` relationship. My ContractSerializer is defined as follows:

```ruby
class ContractSerializer
  include FastJsonapi::ObjectSerializer

  has_many :tenants, serializer: ::LegalEntitySerializer, record_type: 'tenant'

  attribute :uuid
  attribute :start_date
  attribute :payment_day
  attribute :rent
end
``` 

As shown in the Serializer definition, I would like to set the record_type for tenants to 'tenant' and not 'legal_entity'. However, when trying to run `ContractSerializer.new(Contract.limit(1), {include: ['tenants']}).serializable_hash` i get the following results:

![image](https://user-images.githubusercontent.com/24428618/42693298-007da0ee-86af-11e8-9347-db2315d08aa4.png)

As you can see, the record_type: 'tenant' works on 'relationships' array but not on the 'included' array. I am wondering if this is a normal behaviour of the gem?

Thanks in advance for your help!

**Comment by TrevorHinesley** [comment]
From looking at your code, the record_type should be `legal_entity`. If your tenants are `legal_entity` types, then the record_type should be that, not `tenant`.

**Comment by shishirmk** [comment]
@aphilippartd if you want to change the type in the included record as well, then go ahead and use `set_type` in the LegalEntitySerializer definition.

https://github.com/Netflix/fast_jsonapi#serializer-definition

**Comment by Erol** [comment]
I think this might be related to what I encountered on #271 where inherited serializers do not have a set `record_type` by default.

This is the commit with test case: https://github.com/Netflix/fast_jsonapi/pull/271/commits/e7dc8b4b31857c39295bdd5310e00d6a490ba6ce

**Comment by aphilippartd** [comment]
Thanks for your replies! @Erol , you're right, that's most likely the issue thanks!
