### ISSUE TITLE
Deserialization Support

### ISSUE THREAD

**Issue by NickBeukema** [Netflix/fast_jsonapi#28]
When working with AMS, I find it very useful to be able to deserialize my incoming Json API requests. After looking through the library, it looks like this is not an option. Am I missing something, or is there a reason that deserialization is left out?

This library looks great! I'm using this on my next project, will just need AMS in tandem to deserialize for now. Thanks!

**Comment by sriniwasgr** [comment]
@NickBeukema we wanted to get all the major serialization features in this release.  The plan was never to support every AMS feature, but only to support the key ones at a greater speed and then iteratively enhance the gem to provide additional functionality.

Please continue to supplement with other gems in tandem for your deserialization needs.

**Comment by shishirmk** [comment]
@NickBeukema just adding to @sriniwasgr's reply to deserialize params we use this gem https://github.com/Netflix/restful-jsonapi

**Comment by grant-roy** [comment]
Would like to second that deserialization support would be great!

**Comment by niuage** [comment]
One more vote for supporting deserialization :) I'll try using restful-jsonapi in the meantime, thanks.

**Comment by Mirk32** [comment]
any updates for Deserialization??

**Comment by benlieb** [comment]
Any updates?

**Comment by stas** [comment]
I added support for deserialization to https://github.com/stas/jsonapi.rb#deserialization

The initial version is mainly to help folks transition easily from AMS, but I'm open to explore more generic deserialization results.
