### ISSUE TITLE
Slower performance than AMS with associations

### ISSUE THREAD

**Issue by TrevorHinesley** [Netflix/fast_jsonapi#282]
Basically, we just tested our production application with fast_jsonapi, and discovered that AMS actually seems (don't have proper compiled benchmarks other than the stats I'm about to mention, but wanted to start this conversation) faster when lots of associations are used. I'm not sure where to start with speeding that up in fast_jsonapi, but there are noticeable slow-downs when associations are used, to the point where our identical AMS implementation (with even less cached columns than our new fast_jsonapi implementation--we're actually using some cached strings and integer IDs to save on costly string concatenation and database queries that AMS used to do at serialization time in our old implementation) was noticeably faster. On a large endpoint with a ~100kb response document (10 records, with 100 associations included), we're seeing 1.7s response times, whereas AMS was consistently 1.2s.

Happy to help with this, but I'm fairly confident there's something up with included associations, or relationships in general.

**Comment by shishirmk** [comment]
@TrevorHinesley one of the first steps is to get a benchmark or performance test example. I would love to figure out why it would be slow.

**Comment by TrevorHinesley** [comment]
Definitely, we are going to try to set up some benchmark tests tomorrow and early next week. I’ll report back as soon as I have those.

**Comment by TrevorHinesley** [comment]
Sorry about this, it turned out there was a single point of failure that was causing this that was unrelated to fast_jsonapi. It's still slightly faster with fast_jsonapi (takes about 60% of the time that AMS does). Red herring!
