### ISSUE TITLE
has_many :relations, serializer: My::Custom:Serializaer does not work

### ISSUE THREAD

**Issue by kgeoir** [Netflix/fast_jsonapi#307]
Hello,

  I just try to use a specific serializer in a relationship but it does not work. When I check in the code, it seems it is not implemented attribute @serializer is not used in relationship.rb.
Am I mistaking? Do you plan to implement it?

**Comment by manojmj92** [comment]
@kgeoir can you give us the code example of what you have tried to implement? It is hard to give a solution without knowing what you have tried.

**Comment by ankit8898** [comment]
@kgeoir Also, can you provide details on ur implementation and errors? Want to be sure that the one bug we observed related to `serializer:` is same as yours.

**Comment by kgeoir** [comment]
Hello,
Sorry for the delay, holidays power ^^
So what I am trying to do is to define a relation in my serializer when this relation is used, an other serializer is used to render data.
Let me give you this exemple:

`
class BookSerializer
      include FastJsonapi::ObjectSerializer
      attributes :color, :nb_words
end

class StudentSerializer
      include FastJsonapi::ObjectSerializer
      has_many :books, serializer: BookSerializer
end
`
Expected result would be:
`
{
  student: { id: , type: }
  books: [
{id:, type:, attributes: {color: , nb_works:}}, {id:, type:, attributes: {color: , nb_works:}}
]

`

Is that the purpose of the serialize filed ? Because when I try it, I dont have attributes in books.

**Comment by ChrisHampel** [comment]
are you passing in in options[:include]=[:books] as shown here? https://github.com/Netflix/fast_jsonapi#compound-document

**Comment by ankit8898** [comment]
@kgeoir as @ChrisHampel mentioned you need to `include: [:books]` while serialization. Eg

```ruby
StudentSerializer.new(@student_object,{include: [:books]}).serialized_json
```

**Comment by shishirmk** [comment]
@max-larue please go ahead and add that to the read me. I think that is useful to have it in there.

**Comment by kgeoir** [comment]
Hello,
  So I finally got the opportunity to dig a little in the topic. Actually here is what I dont like/dont understand in this solution:
1- If I declare the has_many in the serialize but dont use (without include: [:books]) I still have call to books done which I dont want since it is not a requested data
2- When I call, the data are included in an external array call included so I have to rebuild the relationship on the client side to get all the data. I don't understand why data are not simply added to the main obj. I with to have attributes directly in the relationship and not outside, like this:

`
student: {
   id:  "2168209035", type: "Student",
  attributes: { 
       name: "John McCain"
},
relationships: {
  books: [
{id: , type: 'books', attributes: {....} }
]

I understand that this pattern is recommended by the http://jsonapi.org/ but is it a good design?

**Comment by damien-roche** [comment]
Damn. This is a glaring design issue that can't be ignored. It has sunk my confidence in jsonapi that's for sure. Why on earth would a nested data structure be separated and force me to rebuild on the client as above mentions?

What was supposed to add standardisation has added yet more needless complexity, and I've just got done replacing my AMSs with this gem. Ugh. I guess I can only commend you for sticking with the spec. Open to alternatives if anyone has suggestions.

**Comment by max-larue** [comment]
Just write your own custom serializers that don't implement the jsonapi spec. There's a lot of good code in this gem that you can pull out into your own classes/modules/serializers. Pipe the output from your serializers directly to `OJ.dump` in your controller. We did this and saw big performance improvements. Take a look at their performance methodology, too.

**Comment by damien-roche** [comment]
Good point!
