### ISSUE TITLE
Support for many-to-many relationships

### ISSUE THREAD

**Issue by danascheider** [Netflix/fast_jsonapi#308]
Hi there! I was looking into this gem for my app but it looks like it won't work since we use `:has_and_belongs_to_many` on three of our models. I wanted to see if support for many-to-many relations is functionality you are considering/would consider adding, or if there's a reason (besides these associations being less common) that it isn't currently supported. If you'd like help adding this, I'd be glad to work on it, but I probably couldn't do it without some help since I'd have a lot to learn about both serialization and ActiveRecord internals.

**Comment by danhunter** [comment]
@danascheider Using `has_many` for `has_and_belongs_to_many` relations has worked well for me

**Comment by danascheider** [comment]
Oh fantastic! I haven't had to use many-to-many relations in Rails very much, surprisingly, so I just assumed it was different since the docs didn't mention it. Thank you!
