### ISSUE TITLE
Serializer not working!

### ISSUE THREAD

**Issue by SKEPDIMI** [Netflix/fast_jsonapi#309]
Hi - this is my first time using fast_jsonapi. I am currently building a simple todo API and followed all the instructions provided for usage in the README.md

# Added to Gem file

```
# Active Object JSON serializer
gem 'fast_jsonapi'
```

# Ran bundler

`$ bundle install`

# Generator

`$ rails g  serializer Todo`

# Model Definition

```
# app/serializers/todo_serializer.rb
class TodoSerializer < ActiveModel::Serializer
  include FastJsonapi::ObjectSerializer
  attr_accessor :id, :title, :created_by, :created_at, :updated_at

  has_many :items
end
```

When a request like `GET /todos/1` comes through, it will go through this process (minified):
```
@current_user = User.find(:user_id) # works perfectly
# =>
@todo = Todo.find(params[:id]) # will return the todo
# =>
def show
  if @todo
    render json: @todo, status: :ok
  end
end
```

Expected:
```
{
  "id": 1,
    "title": "Debug some code",
    "created_by": "2",
    "created_at": "2018-08-27T22:26:09.253Z",
    "updated_at": "2018-08-27T22:26:09.253Z",
   "items": [
      {
        "id": 1,
        "name": "Fix serialization",
        "done": false,
        "todo_id": 1,
        "created_at": "2018-08-27T22:26:50.736Z",
        "updated_at": "2018-08-27T22:26:50.736Z"
      }
   ]
}
```

Received:
```
  {
    "id": 1,
    "title": "debug",
    "created_by": "2",
    "created_at": "2018-08-27T22:26:09.253Z",
    "updated_at": "2018-08-27T22:26:09.253Z"
  }
```

This is the Item model:
```
class Item < ApplicationRecord
  belongs_to :todo

  validates_presence_of :name
end
```

And the expected item will work when we request to this route:
```
# id is 1
@item = Item.find(params[:id])
# =>
render json: @item, status: :ok
```

I have a repository with the code [here](https://github.com/SKEPDIMI/todo-api)

Any help is appreciated by this n00b

Thanks in advance

**Comment by ChrisHampel** [comment]
the output you are getting is from rails default implementation `as_json`

As shown in the documentation you currently have to explicitly call the serializer:
```ruby
def show
  if @todo
    render json: TodoSerializer.new(@todo).serializable_hash, status: :ok
  end
end
```

**Comment by SKEPDIMI** [comment]
Thank you very much, @ChrisHampel ! This has solved my issue!
