### ISSUE TITLE
Shame

### ISSUE THREAD

**Issue by estepan** [Netflix/fast_jsonapi#31]
insolent lie
```$ rspec
Active Model Serializer serialized 250 records in 138.71 ms
Fast JSON API serialized 250 records in 3.01 ms
```

**Comment by grossadamm** [comment]
I'm confused, do you disagree with the benchmarks or the methodology?

**Comment by grossadamm** [comment]
I'm going to close this. If you can provide additional clarification, I would be happy to re-open and discuss more.
