### ISSUE TITLE
Allow blocks for setting id

### ISSUE THREAD

**Issue by mikemarsian** [Netflix/fast_jsonapi#315]
Currently we allow to customize any attribute by using blocks. I would like to extend the same behaviour to ids. Currently the only way to customize id is by using `set_id :custom_id` but this specifies an alternative method in the object. Instead, I would like to be able to customize id right here in the serializer, using something like this:
```
class MovieSerializer
  include FastJsonapi::ObjectSerializer

  attributes :name, :year
  set_id do |record|
    "This will be a string ID with #{record.id} inside"
  end
```
This is useful in situations when you have different types of objects (say, `Movie`, `MovieBuilder`, `BaseMovie`) being serialized using the same serializer (`GeneralMovieSerializer`), and you want to unify their ids setting code. What do you think?

**Comment by shishirmk** [comment]
That sounds like a good idea. We should support that. If you can work on it, go ahead and make a pull request.
