### ISSUE TITLE
Migrating from active_model_serializers to fast_jsonapi

### ISSUE THREAD

**Issue by jpamarohorta** [Netflix/fast_jsonapi#316]
Hello, thanks amazing work on this gem! The performance improvements comparing to AMS are really impressive so we are migrating from it.

To ease our migration we didn't wanted to change the JSON output. However the default JSON structure produced by this gem is something along this:

```
{
  "data": [
    {
      "id": "1",
      "type": "model_1",
      "attributes": {
        "id": 1,
        "model_att_1": "foo"
        "mode_att_2": "bar"
      },
      "relationships": {
        "model_1_association": {
          "data": [
...
```

while with AMS the structure was more basic:

```
{
  "model_1s": [
    {
      "id": 1,
      "model_att_1": "foo",
      "mode_att_2": "bar",
      "model_1_association": [
        {
          "id": 3
...
```

Is there any way to change the JSON structure to match the AMS one?

Thanks!

**Comment by devmarwen** [comment]
This gem serializes data based on the [**JSON API** specs](http://jsonapi.org/). I think with **AMS** you are using the `attributes` adapter? If you change the adapter to `json_api` you will basically get the same result as **fast_jsonapi**:
```ruby
ActiveModelSerializers.config.adapter = :json_api # Default: `:attributes`
```

**Comment by manojmj92** [comment]
+1 to what @devmarwen mentioned. You are probably not using AMS with the `json_api` adapter.

**Comment by jpamarohorta** [comment]
Ok I understand now. So it is possible to change AMS JSON adapter to be the same as the `fast_jsonapi` one, but I suppose it is not possible to do the opposite, change the `fast_jsonapi` adapter to `attributes` right? given the name of the gem

**Comment by manojmj92** [comment]
That's right.

**Comment by chrisfairc** [comment]
@jpamarohorta Hi! I am facing a similar issue. How did you go about doing this migration? 

I like the idea of first migrating to use the `json_api` adapter in AMS, and then to `fast_jsonapi`, however how can you continue to support old API clients while using `json_api` format for new clients if it is a global ActiveModelSerializers.config change?

**Comment by chrisfairc** [comment]
I guess I will have to run a second API server for this...

**Comment by jpamarohorta** [comment]
I ended up not migrating that project because it would be too much of a cost for the frontends

**Comment by chrisfairc** [comment]
ah ok. Thanks.

**Comment by jpamarohorta** [comment]
However, I started a new project with `fast_jsonapi` and ended up using this [article](https://medium.com/soundstripe-engineering/greener-pastures-migrating-a-production-api-from-activemodel-serializers-to-fast-json-api-9627be51c64) as a reference, it's useful to get a grip on what changes.

**Comment by chrisfairc** [comment]
Thanks! Kind of getting it working now.
