### ISSUE TITLE
Question: why juwelier

### ISSUE THREAD

**Issue by wilsonsilva** [Netflix/fast_jsonapi#32]
The gemspec of `juwelier` is a mess. What are the advantages of it and running `rake gemspec` every time vs the regular Bundler gemspec?

**Comment by grossadamm** [comment]
I believe we tried to use `juwelier` because at a quick glance it seemed like it offered some good patterns. In practice though, I agree with you and it will likely be removed.

**Comment by guilleiguaran** [comment]
This can be closed since #40 was merged.
