### ISSUE TITLE
Release cycle, next release date?

### ISSUE THREAD

**Issue by jmgarnier** [Netflix/fast_jsonapi#321]
Dear maintainers,

At @nedap we are quite eager to try `fast_jsonapi` but we are waiting for a new release for a fix which is  in your `dev` branch.

Would you be so kind to let the rest of the world know about your release cycle? Nothing urgent, here :)
I guess we can always fork and release a new version in our private gemfurry ...

Thanks anyway for sharing your work.

JM

**Comment by shishirmk** [comment]
@jmgarnier I released a new version yesterday night https://github.com/Netflix/fast_jsonapi/releases/tag/1.4

There is only 1 fix that is in dev that hasn't gone out after yesterday's release. It this fix https://github.com/Netflix/fast_jsonapi/pull/313 If this is needed urgently. I can make a quick patch release 1.4.1

We don't have a fixed release cycle. We generally release when a new highly requested feature is ready and has all the necessary things. We do patch releases more frequently if they patch major issues that are affecting many teams.

**Comment by shishirmk** [comment]
Next version https://github.com/Netflix/fast_jsonapi/releases/tag/1.5 has been released.
