### ISSUE TITLE
Paginate relations

### ISSUE THREAD

**Issue by Mziserman** [Netflix/fast_jsonapi#323]
Hello, 

I'm using fast_jsonapi on a project and was wondering how to paginate relations without breaking the logic.

Currently, I have those serializers : 
```ruby
class EventTypeSerializer
  include FastJsonapi::ObjectSerializer
  attributes :id, :name

  has_many :events,
    if: Proc.new { |record| record.events.any? },
    serializer: EventSerializer
end
```

```ruby
class EventSerializer
  include FastJsonapi::ObjectSerializer

  attributes :id, :name

  belongs_to :event_type,
    if: Proc.new { |record| record.event_type.present? },
    serializer: EventTypeSerializer
end
```
and this controller
```ruby
class EventTypesController
  def show
    @event_type = EventType.find(params[:id])
    @options = {
      include: [:events], # can i do something at this level ?
      is_collection: false
    }
    render json: EventTypeSerializer.new(@event_type, @options).serialized_json
  end
end
```
The issue is some event type have thousands of events.
My question is, how can I paginate events on the event_type show view. Should I make a custom attribute for events in EventTypeSerializer ? Then events won't show in relationships. Should this logic be in the controller ?

**Comment by shishirmk** [comment]
One way i think of doing this is by sending links to page 1 instead of the ids https://github.com/Netflix/fast_jsonapi#links-on-a-relationship
