### ISSUE TITLE
Problem with jsonapi template

### ISSUE THREAD

**Issue by mhi20** [Netflix/fast_jsonapi#325]
Hi 
Can I not use the Jsonapi template?
Can I use a regular template?
**For example :** 
{
 "title":"blah blah",
 "address": "blah blah",
  "images":[
    {
      "url":"http:// blah blah"
     },
     {
       "url":"http:// blah blah"
     }
   ]
}

**Comment by ryano3000** [comment]
would be great if there was support for this

**Comment by manojmj92** [comment]
@mhi20 @ryano3000 Unfortunately, this gem deals only with implementing the JSON API spec(https://jsonapi.org/), so implementing this is out of scope of this gem.
