### ISSUE TITLE
Serializing non-persistent relationships

### ISSUE THREAD

**Issue by zinosama** [Netflix/fast_jsonapi#328]
Dear maintainers,

Given
```ruby
Class Foo
  has_many :bars
end

foo = Foo.new
foo.bars.build(...)
foo.bars.build(...)
```

When I run `FooSerializer.new(foo,{include: %i(bar)).serialized_hash`, I expect the `included` section to have a length of 2 (2 bar object serializations). However, there is only 1 because non of the objects are persisted and thus both ids are nil. Since `known_included_objects` caches 'known' objects, the 2 bar objects are considered as the same object and thus only 1 is serialized.

I understand the reasoning behind the current implementation. Though I'm wondering if you guys ever came across the same issue and have any recommended solution?

Would setting a random value in `id_from_record` when `record.id` returns nil be a reasonable solution? Is there any risk to this?

_ps. I'm serializing non-persistent records because my checkout and place-order uses the same services. The only difference is that checkout doesn't save all the 'built' records - but it still needs to serialize all the associations so that the client can display the checkout view._

**Comment by manojmj92** [comment]
Hi @zinosama ,

thanks for raising this issue! It is a very valid point and this is a usecase that many people will have. However, according to JSON API Spec, every object is supposed to have an ID without exceptions, so this is why we check for `known_included_objects` based on their ID. (Please see this: https://github.com/json-api/json-api/issues/648)

However, you have a workaroud here, thanks to @larissa's PR #331 

Once this is merged, you'd be able to define an ID to your non-persistent objects right inside your serializer and it should work just fine: For eg, something like:

```ruby
class MovieSerializer
  include FastJsonapi::ObjectSerializer
  set_id :id do |record|
   # return id for persistent models, else return random value for non persisent records
   record.id || SecureRandom.uuid 
  end
end
```

If you cannot wait till this PR is merged, you can create another method in your model and do this

```ruby
class Movie
  def id_for_serializer
    id || SecureRandom.uuid
  end
end

class MovieSerializer
  include FastJsonapi::ObjectSerializer
  set_id :id_for_serializer
end
```

Hope that helps!

**Comment by shishirmk** [comment]
Thanks for answer @manojmj92
