### ISSUE TITLE
set_id isn't respected for relationships

### ISSUE THREAD

**Issue by dudo** [Netflix/fast_jsonapi#338]
I can work around this, but I think this behavior is off. 2 things to report about `set_id`.

If I put `set_id :slug` in a base class or sorts, the children don't seem to care, and still use `:id`.

More importantly, relationships don't use the new id.

    class AccountSerializer < BaseSerializer
      set_id :slug

      attributes :name

      belongs_to :applied_rule, record_type: :rule
    end

    class RuleSerializer < BaseSerializer
      set_id :slug

      attributes :name
    end

This returns 

    {:data=>{:id=>"foo", :type=>:account, :attributes=>{:name=>"foo"}, :relationships=>{:appliedRule=>{:data=>{:id=>"1", :type=>:rule}}}}}

**Comment by Mziserman** [comment]
Hey,

I have the same problem and made a failing spec for it : https://github.com/Mziserman/fast_jsonapi/blob/failing-spec-for-set-id/spec/lib/object_serializer_spec.rb#L186. 

Hope it helps !

**Comment by dudo** [comment]
Better yet, why use `set_id` at all, and just rely on `to_param` on the model? Or is that too presumptuous?

**Comment by MAXGGG** [comment]
@dudo  Hi i'm very new to rails and also ran into this problem. The set_id for children is not working in the relations. Can you share your workaround with me, I tried to_param but no good. Thanks a lot.

**Comment by dudo** [comment]
@MAXGGG you need to set `:id_method_name` on the call, and define the corresponding method on your model.

    belongs_to :applied_rule, record_type: :rule, id_method_name: :applied_rule_slug

Then in your model, for a belongs_to

    class Account
      def applied_rule_slug
        applied_rule&.slug
      end
    end

For a has_many

    def thing_slugs
      things.map &:slug
    end

**Comment by MAXGGG** [comment]
@dudo Thanks for your reply! I ended up adding a delegate in model to set the id, which i think is the same workaround as yours, thanks a lot

**Comment by krsyoung** [comment]
I believe I'm in the same boat as others, and I have a combination of the above configurations:
```ruby
class SearchSerializer
  include FastJsonapi::ObjectSerializer
  set_type :user
  set_id :to_param

  attributes :name, :title

  belongs_to :company, record_type: :company, serializer: CompanySerializer, id_method_name: :to_param
end
```

The odd thing is the `id_method_name` seems to set the id of the company to the `to_param` of the User (vs the company).  So basically I end up with the User `to_param` all over the place which must mean I'm doing something very wrong!

@dudo I must have misunderstood your suggestion?

**Comment by dudo** [comment]
@krsyoung I meant for the underlying code to rely on `to_param`. Those symbols will reference the object you're serializing, not the association. So for each of your belongs_to and has_many, create a method on the object you're serializing of `company_slug`, `topics_slugs`, and `expertise_slugs`, and reference the appropriate association.

**Comment by krsyoung** [comment]
Gotcha, thanks @dudo!  Clever workaround.
