### ISSUE TITLE
Helper methods

### ISSUE THREAD

**Issue by sandstrom** [Netflix/fast_jsonapi#344]
Thanks for a great library! 🏆 

One thing that would be very useful is support for helper methods. Basically, to have the proc blocks evaluated in the context of the serializer instance itself.

Is this something you'd be open to adding?

```ruby
class HorseSerializer < ApplicationSerializer

  # ONLY AN EXAMPLE, NOT REAL CODE

  has_one :stable

  attributes :name, :age

  attribute :urls do |model|
    model.photos.map { |p| image_url(p) }
  end

  private
  def image_url(horse_photo)
    MyLibrary.generate_horse_photo_url(horse_photo)
  end

end
```

**Comment by leemour** [comment]
@sandstrom you can just define a class method (`def self.image_url`) instead of instance method and it'll work. Or use `extend` instead of `include` to mix in module methods, since this code is evaluated in class context, not in instance of the class context.

**Comment by manojmj92** [comment]
@leemour thanks for pitching in on the solution! 👍 🥇 

You're right, we need more documentaiton on this so I've raised #349 towards the same! Please take a look and add your suggestions!

**Comment by sandstrom** [comment]
@leemour Are you sure?

To me it doesn't seem like that's the case:
https://github.com/Netflix/fast_jsonapi/blob/master/lib/fast_jsonapi/attribute.rb#L14

I think you would need something like `my_context.instance_exec(params, &proc)` to have `this` bound to `my_context` inside the block/proc.

**Comment by sandstrom** [comment]
@leemour Thanks, good suggestion + good point on adding it to the readme!

@manojmj92 Thanks, you are correct, my mistake.
