### ISSUE TITLE
Some expansion on README?

### ISSUE THREAD

**Issue by febeling** [Netflix/fast_jsonapi#347]
I was somewhat surprised to find that `has_many` and similar only render `id` and `type`. Would it make sense to spell that out in the README? If so, I'd send a PR. 

I'd also include typical usage with Rails (`render json: ModelSerializer.new(@model)`), and mention that serializers happily accept single instances and most collections as first parameter.

I was probably mislead by some of the introduction, which makes the performance comparison with AMS. That led me to assume features are similar in extent as well. (Maybe they are, if looking at the narrower JSON-API subset?)

**Comment by tugayac** [comment]
@febeling `has_many` and similar only render `id` and `type` per the [JSON API spec](https://jsonapi.org/format/). Specifically:
1. The [top level JSON object](https://jsonapi.org/format/#document-top-level) is a ["Resource Object"](https://jsonapi.org/format/#document-resource-objects).
1. The "Resource Object" may contain a ["Relationships Object"](https://jsonapi.org/format/#document-resource-objects).
1. The "Relationships Object" must have at least `links`, `data`, or `meta` fields. By default, I believe this library returns the `data` field, which is a ["Resource Linkage"](https://jsonapi.org/format/#document-resource-object-linkage). From the spec:
> Resource linkage MUST be represented as one of the following:
>* null for empty to-one relationships.
>* an empty array ([]) for empty to-many relationships.
>* a single resource identifier object for non-empty to-one relationships.
>* an array of resource identifier objects for non-empty to-many relationships.

Finally, a "Resource Identifier Object" contains `id` and `type` fields, as defined [here](https://jsonapi.org/format/#document-resource-identifier-objects).

If you want to return more data regarding the relationship objects, you'll have to make use of ["Compound Documents"](https://jsonapi.org/format/#document-compound-documents). Docs on how to do that with this library is [on the README](https://github.com/Netflix/fast_jsonapi#compound-document).

**Comment by febeling** [comment]
@tugayac thanks for the thorough explanation!
