### ISSUE TITLE
On POST / create : "id is a mandatory field in the jsonapi spec"

### ISSUE THREAD

**Issue by tilo** [Netflix/fast_jsonapi#356]
I'm trying to create a resource, by just passing in the `type` and the `attributes` in the `data` section.

I'm getting an error: "id is a mandatory field in the jsonapi spec"

The JSONAPI docs say:

```
Exception: The id member is not required when the resource object originates at the client and represents a new resource to be created on the server.
```

@shishirmk so why is this required in a POST transaction??
an id does not make any sense for a POST / create

This looks like a bug in fast_jsonapi

**Comment by yo-gen** [comment]
What happened to this?
Faced this today.

**Comment by wellingtonx** [comment]
Same issue here

**Comment by aislanmaia** [comment]
I'm having this problem to serialize objects that naturally doesn't contain id field and active records too.

**Comment by danielb2** [comment]
closed the ticket without any resolution... not helpful

**Comment by incorvia** [comment]
You can define a proc:

```
 set_id ->{ nil }
```
