### ISSUE TITLE
Custom id is not used with a `has_one through` association

### ISSUE THREAD

**Issue by marksiemers** [Netflix/fast_jsonapi#385]
With a `has_one through` association and a custom id set in the associated model's serializer, the custom id is respected in the `included` object, but not in the `relationships` object.

This may be related to #245 

```ruby
class Group < ApplicationRecord
  belongs_to :subscription, optional: true
  has_one :account, through: :subscription
end

class Account < ApplicationRecord
end
```

```ruby
class Account::Serializer
  include FastJsonapi::ObjectSerializer
  set_id :account_number
  ...
end

class Group::Serializer
  include FastJsonapi::ObjectSerializer
  ...
  has_one :account, serializer: Account::Serializer
  ...
end
```

I can try to recreate with a test or provide more detail, but right now I've got to implement a workaround in the next 24 hours before our next release.

**Comment by top4ek** [comment]
I beleive we have same problem. Did you found any workarounds?

**Comment by marksiemers** [comment]
@top4ek - My memory is a little rusty (this was about 15 months ago and I don't work at the same company now), but I think it was something like this:
```ruby
class Group < ApplicationRecord
  belongs_to :subscription, optional: true
  has_one :account, through: :subscription

  def account_number
    @account_number ||= subscription&.account_number
  end
end

class Group::Serializer
  include FastJsonapi::ObjectSerializer
  # ...
  has_one :account, serializer: Account::Serializer, id_method_name: :account_number
  # ...
end
```

**Comment by top4ek** [comment]
We've tried that. It doesn't work at least with STI and polymorphic relations. So decided to change architecture alittle :)

**Comment by marksiemers** [comment]
Yeah, polymorphic relations and STI are a whole different wrench thrown in.

FWIW, Bill Karwin convinced me not to use polymorphic associations (at least when backed by a relational database): https://www.slideshare.net/billkarwin/sql-antipatterns-strike-back/32-Polymorphic_Associations_Of_course_some

Also, check the community supported fork of this gem, it may have better support for what you are looking for.
