### ISSUE TITLE
Support for CamelCase attributes

### ISSUE THREAD

**Issue by pratikpandit05** [Netflix/fast_jsonapi#41]
We're looking at json serializers specifically for serializing a PORO. 

One of the core requirements for serialization is that the snake_cased attribute keys be transformed into CamelCased ones to support the json standards being followed by our organization and also some others like Google, w3resource, schema.org, etc. 

Will such a request be considered for this gem? It can be a special configuration item. If yes, I am open to putting a tech design of sorts

**Comment by shishirmk** [comment]
@pratikpandit05 checkout the pull request. That adds the flexibility to choose any kind of key transform including CamelCase and camelCaseLower

**Comment by pratikpandit05** [comment]
+1. Thank you.

**Comment by MarcusRiemer** [comment]
As the mentioned PR #45 has been merged: Is there any ETA for the version containing the change to be released?

**Comment by shishirmk** [comment]
@MarcusRiemer We are planning to release a 1.1.0 version of the gem soon (in a week or two). We are figuring out if we should release it with custom attributes feature being discussed in pull requests or just the things we have merged so far are enough.

**Comment by iSunRise** [comment]
@shishirmk Hey, thank you for the awesome gem. I tried this feature #45 and think that you should mention in the readme that `set_key_transform` method must be called before `attributes` otherwise it won't work. 
I added `set_key_transform` to the bottom of my serializer and it took some time to realize why it doesn't work.

**Comment by shishirmk** [comment]
Released as a part of version 1.1.0
