### ISSUE TITLE
Issue with accessor with a proc shortcut in ruby 3.0

### ISSUE THREAD

**Issue by andiskiy** [Netflix/fast_jsonapi#478]
when I write like this `attribute :foo, &:bar `, I get an error `wrong number of arguments (given 2, expected 1)`. This is due to the arity of Proc, Lamda in [here](https://github.com/Netflix/fast_jsonapi/blob/master/lib/fast_jsonapi/attribute.rb#L14). Please, fix it.

**Comment by ChrisHampel** [comment]
This library is no longer maintained by Netflix, it is now maintained by the community at https://github.com/jsonapi-serializer/jsonapi-serializer as stated in the Read Me. This issue is fixed there.
