### ISSUE TITLE
Serialization structure

### ISSUE THREAD

**Issue by maxime-d** [Netflix/fast_jsonapi#50]
Hi, 

We works with AMS, and we have many options to customize the serialization output.
Actually the serialization object with `fast_jsonapi` are imposed.

```json
{
  "data": {
    "id": "232",
    "type": "movie",
    "attributes": {
      "name": "test movie",
      "year": null
    },
   ...
}
```

So, do you have any ideas if you wants add more options to changes structure of data, example if I want build : 

> GET /movies/:id
```json
{
   "movie": {
     "id": "232",
     "name": "test movie",
     "year": null
   }
}
```
> GET /movies
```json
{
   "movies": [
    {
     "id": "232",
     "name": "test movie",
     "year": null
    },
    {
     "id": "233",
     "name": "another test movie",
     "year": null
    }
  ],
  "meta": { ... }
}
```

Thanks

**Comment by sriniwasgr** [comment]
@maxime-d I believe you are asking if non json api spec is or will be supported. The answer is no. The gem was designed to work with json api spec to avoid bike shedding.

**Comment by Uysim** [comment]
+1

**Comment by maxime-d** [comment]
@sriniwasgr right, we are not json api / rpc spec compliant, I hope one day my CTO is agree to switch it, but for moment i'm asking if `fast_jsonapi` have any idea if they support another structure ;). Indeed first implementation of `fast_jsonapi` is awesome and good way !

**Comment by shishirmk** [comment]
@maxime-d we are focusing on json api spec right now. There is lot of work to do. So we wont be able to get to it soon.
