### ISSUE TITLE
[Question] How can it be used to serialize error?

### ISSUE THREAD

**Issue by ljieyao** [Netflix/fast_jsonapi#53]
I wonder how can I use it to return an error message with HTTP error?

**Comment by DVG** [comment]
JSONAPI only requires that a top level errors array be returned and has many optional member attributes that you may or may not find useful:

http://jsonapi.org/format/#error-objects

Therefore you should just be able to make an error serializer with as much of the spec that you find useful (code, title, detail, for instance)

**Comment by grossadamm** [comment]
@DVG thanks for chiming in and I agree with your approach. This library does not take an opinionated approach for serializing errors. You could optionally do something as simple as the below (untested) and still be within the json api spec. 

```
data = { errors: [] }
data[:errors] << {id: "movie", title: "invalid title"}
render json: data, status: :unprocessable_entity
```

**Comment by grossadamm** [comment]
I feel like this question has been answered. I'm going to close this for now, please feel free to re-open if you disagree!

**Comment by tommyalvarez** [comment]
For anyone else reaching here like i did... i ended up implementing the following serializer. It supports nested model errors indexed. Manually tested, no rspec, so no guarantees

```
class ErrorSerializer
  def initialize(model)
    @model = model
  end

  def serialized_json
    errors = @model.errors.messages.map do |field, errors|
      errors.map do |error_message|
        {
          source: {pointer: "/data/attributes/#{field}"},
          detail: error_message
        }
      end
    end
    @model.class.reflect_on_all_associations.each do |relationship|
      @model.send(relationship.name).each_with_index do |child, index|
        errors << child.errors.messages.map do |field, errors|
          errors.map do |error_message|
            {
              source: {pointer: "/data/attributes/#{child.model_name.plural}[#{index}].#{field}"},
              detail: error_message
            }
          end
        end
      end
    end
    errors.flatten
  end
end

```

**Comment by Genkilabs** [comment]
Additionally, if you like the JSONAPI error spec and want it for general use beyond errors within a model. You can drop something like this right in application_controller.rb
```
    # CUSTOM GENERAL EXCEPTION HANDLING
    # NOTE: This MUST come before any more specific exception handling. The order of definition is relevant!
    rescue_from StandardError do |e|
        logger.error "ApplicationController: GENERAL ERROR caught #{e}\n #{e.backtrace[0..5].join("\n")}"
        respond_to do |format|
            format.html { raise(e) }
            format.json { 
                error_struct = {:errors => [
                    :status => '500',
                    :code => e.class.to_s,
                    :detail => e.message,
                ]}
                render json: error_struct, status: :internal_server_error
            }
            format.pdf { Rails.env.development? ? raise(e) : redirect_to(root_path, :flash => { :error => "Error rendering page as PDF file" }) }
        end
    end
```
(I threw in PDF to demonstrate the env conditional which I often find useful during dev)

**Comment by pioz** [comment]
It would be awesome to have an implementation of the errors in json api format!

**Comment by KelseyDH** [comment]
```ruby
module Api::V1
  class ApiController < ActionController::API

    around_action :handle_errors

    def handle_errors
      yield
    rescue ActiveRecord::RecordNotFound => e
      data = { errors: [] }
      data[:errors] << {code: 404, details: e.message}
      render json: data, status: :not_found
    rescue ActiveRecord::RecordInvalid => e
      data = { errors: [] }
      data[:errors] << {code: 422, details: e.message}
      render json: data, status: :unprocessable_entity
    rescue JWT::ExpiredSignature => e
      data = { errors: [] }
      data[:errors] << {code: 401, details: e.message}
      render json: data, status: :unauthorized
    end

  end
end
```

This was the pattern we used for rendering errors for this gem, compliant with the JSON API spec.

**Comment by stas** [comment]
Alternatively consider using the `jsonapi.rb` gem which provides error handling for validation errors and other generic cases you can encounter:
https://github.com/stas/jsonapi.rb#error-handling

Since the work is heavily based on the `fast_jsonapi` and the feedback I could find here (hence the small codebase), it should be easy to start using it.

Let me know if you have feedback as well :bowing_man: 

Related issues #102 #408

**Comment by ali-sennalabs** [comment]
I come up with my own serializer

```ruby
class ErrorSerializer
  attr_reader :resource, :errors
  alias_method :serializable_hash, :as_json
  alias_method :serialized_json, :to_json

  def initialize(resource, options = {})
    @resource = resource
    @errors = errors_for(resource).flatten
  end

  def id
    resource.id.to_s
  end

  def type
    resource.class.name.downcase
  end

  def serializable_hash(options = nil)
    {}.tap do |hash|
      hash[:id] = id if has_id?
      hash[:type] = type if has_id?
      hash[:errors] = errors
    end
  end

  def serialized_json(options = nil)
    serializable_hash.to_json(options)
  end

  private

  def has_id?
    @resource.respond_to?(:id)
  end

  def errors_for(resource)
    resource.errors.messages.map do |field, errors|
      build_hashes_for(field, errors)
    end
  end

  def build_hashes_for(field, errors)
    errors.map do |error_message|
      build_hash_for(field, error_message)
    end
  end

  def build_hash_for(field, error_message)
    {}.tap do |hash|
      hash[:source] = {pointer: "/data/attributes/#{field}"}
      hash[:detail] = error_message
    end
  end
end
```

**Comment by juanmanuelramallo** [comment]
> @DVG thanks for chiming in and I agree with your approach. This library does not take an opinionated approach for serializing errors. You could optionally do something as simple as the below (untested) and still be within the json api spec.
> 
> ```
> data = { errors: [] }
> data[:errors] << {id: "movie", title: "invalid title"}
> render json: data, status: :unprocessable_entity
> ```

This is not JSON:API compatible actually 
From https://jsonapi.org/format/#errors-processing
>Error objects MUST be returned as an array keyed by errors in the top level of a JSON:API document.


_Sorry for chiming it this late_

**Comment by danielb2** [comment]
> This is not JSON:API compatible actually From https://jsonapi.org/format/#errors-processing
> 
> > Error objects MUST be returned as an array keyed by errors in the top level of a JSON:API document.

I think this is exactly why this library _should_ implement errors.
