### ISSUE TITLE
Use primary key instead of hard coding id

### ISSUE THREAD

**Issue by grossadamm** [Netflix/fast_jsonapi#55]
In some cases, the `id` column or attribute is hard coded in. It might make more sense to use the [primary key](http://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/PrimaryKey/ClassMethods.html#method-i-primary_key-3D) or something similar to derive the actual primary key.

**Comment by guilleiguaran** [comment]
Even when using a custom primary key with ActiveRecord `Model#id` always return the value of the primary key, e.g:

```ruby
Post.primary_key
# => "unique_id"
Post.first
#  Post Load (0.2ms)  SELECT  "posts".* FROM "posts" ORDER BY "posts"."unique_id" ASC LIMIT ?  [["LIMIT", 1]]
# => #<Post unique_id: 1, title: "lol", body: "wut", created_at: "2018-02-06 05:36:26", updated_at: "2018-02-06 05:36:26">
Post.first.id
#  Post Load (0.1ms)  SELECT  "posts".* FROM "posts" ORDER BY "posts"."unique_id" ASC LIMIT ?  [["LIMIT", 1]]
# => 1
```

Ref: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/attribute_methods/primary_key.rb#L18-L22

**Comment by franciscomxs** [comment]
👍
