### ISSUE TITLE
`fields` option to choose what attributes will be used in serialization

### ISSUE THREAD

**Issue by youroff** [Netflix/fast_jsonapi#57]
Would be awesome if it was possible to choose what keys will be used to generate json. So that depending on context, using the same serializer, we could render light-version of the model. This is what we used a lot in AMS. If this makes sense, I can provide a PR.

**Comment by shishirmk** [comment]
@youroff I would be happy to look at PR. This is an enhancement that we would like to see in the gem.

**Comment by nurey** [comment]
Would love to see this. This is JSON API sparse fieldsets. http://jsonapi.org/format/#fetching-sparse-fieldsets

**Comment by youroff** [comment]
There's a couple of problems though. On my computer perf tests are randomly failing 50% of times. Which happens without modifications too though.

I'm not sure that it will work if different key_transform was used in different serializers. To fix that, we might instantiate serializers when processing included records, instead of using their internals on the class level. It might affect performance, but bring some safety.

**Comment by shishirmk** [comment]
This feature is released in [version 1.3](https://github.com/Netflix/fast_jsonapi/releases/tag/1.3)
