### ISSUE TITLE
hi，can support rails 3.2?

### ISSUE THREAD

**Issue by aeroyu** [Netflix/fast_jsonapi#68]
hi，can support rails 3.2?

**Comment by shishirmk** [comment]
I am sorry we don't have that on our plans right now.

**Comment by FutoRicky** [comment]
@shishirmk Does it support rails 4.2? Or just rails 5?

**Comment by guilleiguaran** [comment]
Rails 4.2 will be supported in next release

**Comment by guilleiguaran** [comment]
1.1 is released, this can be closed

**Comment by nitinkhairnar** [comment]
Hi,
Do this gem supports rails version '3.2.14'?
