### ISSUE TITLE
Make `belongs_to` an alias of `has_one`

### ISSUE THREAD

**Issue by vovimayhem** [Netflix/fast_jsonapi#73]
Looking at the code, there's no real difference for an association being `belongs_to` and  `has_one`. Instead, is a source for problems (two places with the same code are two places you can forget to place a fix.. have you noticed the [default serializer is obtained differently?](https://github.com/Netflix/fast_jsonapi/blob/dev/lib/fast_jsonapi/object_serializer.rb#L188)). Both do the same thing, and both cause the same consequences in the serialization core.

Also, the jsonapi doesn't care about the direction of a 1-to-1 association.

How about:

* Removing the [`belongs_to`](https://github.com/Netflix/fast_jsonapi/blob/dev/lib/fast_jsonapi/object_serializer.rb#L186) method in `object_serializer.rb`
* Adding `belongs_to` as an alias of `has_one`, so it is backwards-compatible.

**Comment by shishirmk** [comment]
@vovimayhem That is a very nice way to refactor some of the repetition we have in the code today. You are right as far JSON:API is concerned i don't think there is any distinction between belongs_to and has_one. I think we should work on this idea.

**Comment by amrrbakry** [comment]
I think I can help with this. I will open a PR soon :+1:

**Comment by vovimayhem** [comment]
Hey
I've got a commit with that on another PR (Sorry!)

**Comment by vovimayhem** [comment]
c5295e6

**Comment by amrrbakry** [comment]
No problem. Good work 👍

**Comment by shishirmk** [comment]
This should be released in version 1.2 of the gem

**Comment by ababich** [comment]
I think this is a big problem when `has_one` and `belongs_to` are aliased they are logically different and it should be implemented:

A `belongs_to` B means A has `b_id` attribute
A `has_one` B means B has `a_id` attribute

Current implementation when you have to provide additional attribute for `has_one` relation is pretty inconvenient

**Comment by abevoelker** [comment]
I agree with @ababich and created #257 for consideration

**Comment by vovimayhem** [comment]
@ababich @abevoelker IMHO the direction/cardinality of the association in the database shouldn't be relevant on the serialization part of JSONAPI.

In both cases, you get the associated object's `id` and `type`, regardless if the ActiveRecord/ORM model your'e serializing has it implemented as a `belongs_to` or a `has_one`. There should be no extra attributes/options required to declare on the serializer.

**Comment by ababich** [comment]
@vovimayhem 

`fast_jsonapi` **always** expects `_id` field in model A which is inconvenient in lots of one-to-one associations

for example:

we have base model `A` and with one-to-one relation with model `AHeavyDatails` and model `AStats`

both `AHeavyDatails` and `AStats` have `a_id` field

Having `a_id` in "extension" models is more scalable, etc. but, anyway, this is existing DB design

to describe this design, `belongs_to` and `has_one` are used in all popular ORM which helps to describe this logic

I see no reason why `fast_jsonapi` cannot follow similar convention

what's more, in terms of API it is very convenient to requiest model `A` and optionally include `AHeavyDatails` and/or `AStats` from example above.
