### ISSUE TITLE
Mistakenly made issue

### ISSUE THREAD

**Issue by cohei** [Netflix/fast_jsonapi#78]
Mistakenly made issue

**Comment by shishirmk** [comment]
@cohei I cannot read Japanese. So I tried using google translate to understand your question. The translation was very bad and I dont think i understood your question. Here is the translation i got.

```
```

**Comment by cohei** [comment]
@shishirmk 
Sorry, I mistook this repository for our repository and mistakenly made this issue. Please forget about it.
