### ISSUE TITLE
Serializer Inheritance doesn't copy attributes

### ISSUE THREAD

**Issue by eprothro** [Netflix/fast_jsonapi#79]
It's not clear that the following won't work as might be expected:

```
class UserSerializer
  include FastJsonapi::ObjectSerializer

  attribute :first_name
  attribute :last_name
end
```
```
class FullUserSerializer < UserSerializer

  attribute :birthday
  attribute :email
end
```

Workaround:

```
class UserSerializer
  include FastJsonapi::ObjectSerializer

  def self.inherited(subclass)
    subclass.attributes_to_serialize ||= {}
    subclass.attributes_to_serialize.merge!(attributes_to_serialize)
  end

  attribute :first_name
  attribute :last_name
end
```

**Comment by DEfusion** [comment]
This also got me too, I'm working around it right now but was going to look at getting it to work properly without hacks later.

**Comment by guilleiguaran** [comment]
I think we can fix this converting the attribute definitions in proper methods definitions (@shishirmk played with the idea in https://github.com/Netflix/fast_jsonapi/pull/67/files#diff-34088120ad9556cc6578b0c51b38c723R150)

I think we can discuss this as part of the broad architecture discussion that we are having in https://github.com/Netflix/fast_jsonapi/issues/71

**Comment by christophersansone** [comment]
@eprothro Good catch!  These class instance variables such as `@attributes_to_serialize` are scoped to the class itself and pay no attention to the parent classes.  I tried a few things, narrowed it down to two possible implementations.

The first is straight from @eprothro's work above, where we initialize everything from the superclass to the descendant within the `inherited` method:

```ruby
class Base
  def self.inherited(subclass)
    super(subclass)
    attributes_to_serialize.each { |a| subclass.attribute(a) }
  end

  def self.attributes_to_serialize
    @attributes_to_serialize ||= []
  end

  def self.attribute(val)
    attributes_to_serialize << val
  end

  attribute :foo
  attribute :bar
end

class Subclass < Base
  attribute :baz
end

class SubSubclass < Subclass
  attribute :boo
end

Base.attributes_to_serialize  # [:foo, :bar]
Subclass.attributes_to_serialize # [:foo, :bar, :baz]
SubSubclass.attributes_to_serialize # [:foo, :bar, :baz, :boo]
```

The second approach is to define the accessor methods to read from its superclass:

```ruby
class Base
  def self.base_serializer
    return @base_serializer if @base_serializer_loaded
    @base_serializer_loaded = true
    @base_serializer = superclass if superclass && superclass.respond_to?(:base_serializer)
  end

  def self.attributes_for_serialization
    @attributes_for_serialization ||= base_serializer ? base_serializer.attributes_for_serialization.dup : []
  end

  def self.attribute(val)
    attributes_for_serialization << val
  end

  attribute :foo
  attribute :bar
end

class Subclass < Base
  attribute :baz
end

class SubSubclass < Subclass
  attribute :boo
end

Base.attributes_to_serialize  # [:foo, :bar]
Subclass.attributes_to_serialize # [:foo, :bar, :baz]
SubSubclass.attributes_to_serialize # [:foo, :bar, :baz, :boo]
```

Both methodologies seem to work throughout the inheritance chain.  And they both happen at load time, so performance will be optimal.  I would probably lean towards the second approach because it seems more explicit to understand where exactly this variable comes from.

**Comment by eprothro** [comment]
Both LGTM. 

I personally find the former example more idiomatic/clear since 
  * We don't currently need `base_serializer` for any other reason after first `attributes_for_serialization` call.
  * The attribute inheritance is done _directly_ upon inheritance (`self.inherited`) instead of making the assumption that `attribute` is called _very soon after_ inheritance.

**Comment by christophersansone** [comment]
Thanks @eprothro, sounds good.  Pretty much anything that has been set in the superclass will need to be migrated to the subclasses: attributes, relationships, key transformation, etc.  It could make `self.inherited` quite large over time, but you're right that everything would happen immediately, and all inherited properties are encapsulated in one method.

**Comment by shishirmk** [comment]
@christophersansone @eprothro I also like the former approach. I think it would be good to fix this issue now since  version `1.1.0` is released and we can make a patch release with this fix. 

It would be great if one of you made a pull request as you have faced the issue first hand

**Comment by shishirmk** [comment]
This should be fixed for attributes, relationships, links etc. Try version 1.2 of the gem

**Comment by mhluska** [comment]
@shishirmk are there plans to make this work for `set_type`? I find I still have to declare `set_type` all the way down the inheritance chain.

**Comment by manojmj92** [comment]
@shishirmk it would be nice if you can make this work for both `set_type` and `set_id`. I can work on this.

**Comment by jackhayter** [comment]
@manojmj92 Sorry for re-awakening this dead thread, but did you ever figure out a way to get `set_id` to behave like that?
