### ISSUE TITLE
Benchmarks are misleading. I get only 2.5x AMS, and only 1.05x jsonapi-rb

### ISSUE THREAD

**Issue by NullVoxPopuli** [Netflix/fast_jsonapi#81]
I just did my own benchmarks, and I'm suuuuper open to others checking my work.
But this is what I got (using default settings):

##### iterations per second
```
Comparison:
  fast_jsonapi eager:      547.9 i/s
  jsonapi-rb   eager:      521.4 i/s - 1.05x  (± 0.01) slower
  ams          eager:      219.0 i/s - 2.50x  (± 0.02) slower
                   with 95.0% confidence
```

##### memory allocation
```
Comparison:
  fast_jsonapi eager:      96234 allocated
  jsonapi-rb   eager:     109874 allocated - 1.14x more
  ams          eager:     249662 allocated - 2.59x more
```

that memory allocation is pretty good though. :-D

Here is the repo where I made the benchmark:
https://github.com/NullVoxPopuli/ruby-jsonapi-benchmarks

Something that _needs_ to be benchmarked is nested includes performance... 
AMS and jsonapi-rb both support nested includes. (and this is where jsonapi-rb beats the pants of AMS). :-)

For example: 
1 User, 20 Posts, 20 Comments per Post - including `'posts.comments'`
```
Comparison:
  jsonapi-rb   eager:       22.6 i/s
  ams          eager:        4.6 i/s - 4.91x  (± 0.04) slower
                   with 95.0% confidence

Comparison:
  jsonapi-rb   eager:    3979876 allocated
  ams          eager:   12287098 allocated - 3.09x more

```

**Comment by shishirmk** [comment]
@NullVoxPopuli  We have outlined the methodology and the reasoning of our benchmark tests in this [document](https://github.com/Netflix/fast_jsonapi/blob/master/performance_methodology.md). It outlines what tradeoffs we are making to get better performance.

I took a quick look at benchmark [repo linked](https://github.com/NullVoxPopuli/ruby-jsonapi-benchmarks) above. I noticed that you are serializing only one record in each iteration. That is not the use case fast_jsonapi is optimized for. Like we say in the document one of the things we optimize for is [homogeneous lists of objects](https://github.com/Netflix/fast_jsonapi/blob/master/performance_methodology.md#prologue).  So i modified the benchmark to run homogenous lists of user objects and removed nested includes to keep the outputs as similar as they can be for all three libraries here are the results for iterations per second metric.

```
Serializing 1 records
Comparison:
  fast_jsonapi eager:    20933.2 i/s
  jsonapi-rb   eager:     5526.4 i/s - 3.79x  (± 0.11) slower
  ams          eager:      552.0 i/s - 37.90x  (± 1.24) slower
                   with 95.0% confidence

Serializing 25 records
Comparison:
  fast_jsonapi eager:     1965.0 i/s
  jsonapi-rb   eager:      751.7 i/s - 2.61x  (± 0.09) slower
  ams          eager:       94.9 i/s - 20.71x  (± 0.35) slower
                   with 95.0% confidence


Serializing 250 records
Comparison:
  fast_jsonapi eager:      213.9 i/s
  jsonapi-rb   eager:       85.9 i/s - 2.49x  (± 0.07) slower
  ams          eager:       11.9 i/s - 17.97x  (± 0.24) slower
                   with 95.0% confidence


Serializing 1000 records
Comparison:
  fast_jsonapi eager:       53.2 i/s
  jsonapi-rb   eager:       21.7 i/s - 2.45x  (± 0.05) slower
  ams          eager:        3.0 i/s - 17.55x  (± 0.30) slower
                   with 95.0% confidence
```

[Link to the gist](https://gist.github.com/shishirmk/904379f99a64e2f24a055d89e08fd057) with files i changed to support homogenous lists.

I feel like the results are roughly the same as shown in our benchmark performance tests. I hope that clears any questions about the benchmarks being misleading.

**Comment by NullVoxPopuli** [comment]
That's fair. The original benchmark was against flat lists -- good distinction.
I'd argue that testing relationships is a bit more of the 'common scenario'. It's interesting how much of a difference there is between having 1 primary resource, vs a list. For example, with 25 users including 20 posts each:

```
# equiv of GET /api/users?include=posts

# configured to have the same output (inefficient for everybody except fast_jsonapi)
Comparison:
  fast_jsonapi eager:      114.7 i/s
  jsonapi-rb   eager:       24.8 i/s - 4.63x  (± 0.07) slower
  ams          eager:        3.1 i/s - 36.62x  (± 0.56) slower
                   with 95.0% confidence

# with defaults for each gem
Comparison:
  fast_jsonapi eager:      100.7 i/s
  jsonapi-rb   eager:       38.5 i/s - 2.62x  (± 0.05) slower
  ams          eager:        2.7 i/s - 37.42x  (± 1.07) slower
                   with 95.0% confidence

```

whereas my previous benchmarks were the equiv of `GET /api/users/:id?include=posts`

So, that's interesting. I'm sure a lot of performance is gained by reducing configurability/feature-sets (as compared with jsonapi-rb).

Will be interesting to also benchmark nested includes and sparse fieldsets when those become available in fast_jsonapi.

**Comment by zkwentz** [comment]
> What I've learned from this is that AMS is really bad.

Regarding this last point. I don't think it is that AMS is bad, rather it is not as performant. Furthermore, I think that's okay for it to not be as performant as an alternative that is optimized for performance. AMS is optimizing for something different, namely flexibility.

**Comment by guilleiguaran** [comment]
Agree with @zkwentz, many of the decisions done in AMS in early days were done having as the main motivator the flexibility and seamless integration with ActiveModel/ActionController (this isn't achieved totally by the other alternatives at the moment). AMS supports many features that don't make sense to have when you are using only a single standard as JSON API.

For instance, you can write adapters for Siren, HAL, JSON-LD, Collection+JSON, etc, or even for your custom JSON format in top of AMS (Fun fact: one time I wrote a [Cap'n Proto](https://capnproto.org) adapter for AMS)

**Comment by bf4** [comment]
OT: @guilleiguaran Where's the capnproto adapter? I'd love to see it and hear your experience.
