### ISSUE TITLE
dynamic keys

### ISSUE THREAD

**Issue by jankmet** [Netflix/fast_jsonapi#82]
It's possible to serialize object/hash with dynamic keys?

**Comment by guilleiguaran** [comment]
Can you provide an example to illustrate this better?

**Comment by jankmet** [comment]
asset:
```javascript
{ 
  id: 2232,
  filename: '2232.pdf',
  attributes: {
    key1: val1,
    key2: val2,
    key3: val3
  }
}
```
key1,key2,key3 are dynamic keys from attributes table (asset has many attributes)

**Comment by shishirmk** [comment]
Do you use Active Model Serializers for this today? If yes can you share an example serializer class where you would use this?

**Comment by jankmet** [comment]
No, we are using jbuilder. Serializer with 'attributes' property as hash would probably work,
but I'm not sure how is this hash serialized? Is this 'attributes' hash serialized with fast_jsonapi as well?
```ruby
class Asset
  attr_accessor :id, :name, :attributes
end
```
```ruby
class AssetSerializer
  include FastJsonapi::ObjectSerializer
  set_type :asset
  attributes :name, :attributes
end
```

**Comment by laertispappas** [comment]
@jankmet So your models are as follows:

an assets has many attributes?
```
Asset 1-------* Attribute
```

if so your schema should be something like this:
```ruby
{ 
  id: 2232,
  filename: '2232.pdf',
  attributes: [
    { key1: val1 },
    { key2: val2 },
    { key3: val3 }
  ]
}
```
Which can be modeled with a `has_many`  relationship

**Comment by shishirmk** [comment]
@laertispappas it would be better but it seems to be really tricky to do give our current design. Look at the discussion in #49

**Comment by shishirmk** [comment]
@jankmet I am closing this right now as dynamic keys is not really part of [json:api](http://jsonapi.org/) standard. We need to know all attribute and relationship keys ahead of time in order to support features like sparse field sets and includes.

**Comment by TrevorHinesley** [comment]
Wouldn't this be possible with a block since #54 is merged in?

For instance:

```
# file: asset_serializer.rb
attributes :id, :filename, 
attribute :attributes_as_json do |record, params|
  record.attributes.map{|a| [a.key, a.value]}.to_h
end
```

You could even render certain attributes in that hash conditionally based on params that are passed in from the calling controller/context.
