### ISSUE TITLE
jbuilder support

### ISSUE THREAD

**Issue by jankmet** [Netflix/fast_jsonapi#83]
I was wondering how can I use fast_jsonapi with jbuilder. I Probably need new adapter in multijson,
problem is that multijson is fast_jsonapi dependency. It's somehow possible?

**Comment by shishirmk** [comment]
in the next version multi_json is being removed as a dependency. Check out the `dev` branch.

**Comment by jankmet** [comment]
do you think it's worth trying? any chance of performance boost?

**Comment by shishirmk** [comment]
I am not sure if we an use fast_jsonapi in jbuilder right now. It is something we built to be similar to AMS but focused on [jsonapi](http://jsonapi.org/) standard. Since it's focused it faster than AMS. 

I am not sure if it could be even used with jbuilder.

**Comment by guilleiguaran** [comment]
AMS can't be used with jbuilder either, they're mutually exclusive libraries.

If you want to support JSON API standard in jbuilder take a look to this: https://github.com/vladfaust/jbuilder-json_api
