### ISSUE TITLE
Will this conflict with existing 'active_model_serializers' gem?

### ISSUE THREAD

**Issue by bloolizard** [Netflix/fast_jsonapi#87]
Interested in using this gem.  Any conflict with having existing active_model_serializers in app already?

**Comment by shishirmk** [comment]
It shouldn't when we were migrating AMS to fast_jsonapi. We had both in the codebase. We differentiated the serializers by creating separate folders for the two types of serializers

**Comment by bloolizard** [comment]
thnx! will try it out
