### ISSUE TITLE
Allow includes to be strings

### ISSUE THREAD

**Issue by martndemus** [Netflix/fast_jsonapi#91]
Having a `Series` serializer with `has_many :episodes`

```ruby
SeriesSerializer.new(series, include: ['episodes'])
```

Throws an `ArgumentError`.

I would expect it to work, since includes are often pulled from a controller's params, which are always strings.

Having `.to_sym` the strings would also be a memory issue in Ruby before 2.2.

**Comment by sjmog** [comment]
Local pull request created [here](https://github.com/sjmog/fast_jsonapi/pull/1) that seems to demonstrate this error.

**Comment by shishirmk** [comment]
Released as a part of version 1.1.0
