### ISSUE TITLE
Don't require a method called `cache_key` on the model

### ISSUE THREAD

**Issue by aaronmallen** [Netflix/fast_jsonapi#99]
Given the following model:
```ruby
class Foo
  attr_accessor :id, :name
  def initialize(opts = {})
    @id = opts[:id]
    @name = opts[:name]
  end
end
```

and the following serializer:
```ruby
module Api
  module V1
    class FooSerializer
      include FastJsonapi::ObjectSerializer
      set_type :foo
      cache_options enabled: true, cache_length: 12.hours
      attributes :id, :name
    end
  end
end
```

an error is raised when called with:
```ruby
module Api
  module V1
    class FoosController < ApiController
      def show
        foo = Foo.new(id: 1 , name: 'foo')
        render json: FooSerializer.new(foo).serialized_json, status: :ok
      end
  end
end

#=> undefined method `cache_key' for #<Foo:0x00007f94d880b500>
```

we need to add documentation that this is required for caching or we need to not require it, and I would prefer the later.  If cache_key is not defined we should assume a `cache_key` of the object name and id (in this case `"foo:#{object.id}"`).

**Comment by shishirmk** [comment]
agree we need to make that explicit for now and not make that a requirement eventually

**Comment by laertispappas** [comment]
`cache_key` depends on AR models. How about relationships and `relation_id[s]` method? The client should implement them so i think it makes sense here to let the client implement the  `cache` key as well.

**Comment by shishirmk** [comment]
@aaronmallen Would you like to update the documentation for this?
